seb-oss/green

- libs/charts/src/scss/index.scss
> fix(chart): add stroke color for grid base line

- libs/angular/src/lib/dropdown/popover-element.directive.ts
> fix(angular-dropdown): enable scroll when destroyed

- libs/charts/package.json
- package.json
- tools/executors/scss/impl.js
- tools/executors/scss/impl.ts
- yarn.lock
> fix: compile error

- libs/chlorophyll/scss/components/alert/_index.scss
- libs/chlorophyll/scss/components/alert/_mixins.scss
- libs/chlorophyll/scss/components/input/_validation.scss
- libs/chlorophyll/scss/stories/alert.stories.mdx
- libs/chlorophyll/scss/tokens/_shame.scss
> fix(alert): clean up code, tokens and example

- libs/chlorophyll/scss/components/close/_index.scss
- libs/chlorophyll/scss/components/close/_mixins.scss
> fix(close): clean up

- libs/react/src/lib/form/button.stories.mdx
- libs/react/src/lib/form/buttonGroup.stories.mdx
- libs/react/src/lib/form/form.stories.mdx
- libs/react/src/lib/form/input.stories.mdx
- libs/react/src/lib/form/text.stories.mdx
- libs/react/src/lib/form/text.tsx
add missing storybooks for input, text, button and button group
components
> fix: 🐛 add missing storybooks

- libs/chlorophyll/scss/components/list/_index.scss
- libs/chlorophyll/scss/components/list/_mixins.scss
- libs/chlorophyll/scss/tokens/_shame.scss
> fix(list): refactor mixins and tokens, add support for dark mode

- libs/chlorophyll/scss/components/utility/_colors.scss
- libs/chlorophyll/scss/stories/utilities/colors.stories.mdx
> fix(colors): add utility class for light and dark

- libs/react-charts/.env.local
- libs/react/.env.local
> docs(storybook): fix react storybook

- README.md
> docs: ✏️ added info about seb-win install

- libs/react-charts/.env.local
- libs/react-charts/project.json
- libs/react/.env.local
- libs/react/project.json
> chore(nx): workaround for react storybook build issue

- README.md
#306
Got more problems having it on win10 locally.
> docs: ✏️ Cert, build and global info

- README.md
> Doc/Readme Typos

- README.md
> docs: ✏️ more on cert

- libs/react/.storybook/main.js
- libs/react/src/introduction/install.stories.mdx
- libs/react/src/introduction/use.stories.mdx
> feat: 🎸 Added documentation for green-react-component install

- libs/react/src/lib/modal/modal.spec.tsx
- libs/react/src/lib/modal/modal.stories.tsx
- libs/react/src/lib/modal/modal.tsx
Default modal: 
Slide-out modal:
Take-over modal:
> refactor: 💡 Refactored modal component

- libs/angular-charts/package.json
- libs/angular-charts/project.json
- libs/angular/package.json
- libs/angular/project.json
- libs/charts/package.json
- libs/extract/project.json
- libs/react-charts/project.json
- libs/react/project.json
> build: fix dependencies in package.json for libs

- libs/chlorophyll/scss/components/form/validation/_mixins.scss
> fix(form-validation): margin for error in horizontal forms

- .storybook/main.js
This PR enables a feature in Storybook that generates a json file (/stories.json) that contains an index of all stories. This will be used to display Green components in Design Library.
> chore: enable stories.json feature

- libs/react/src/lib/alert/alert.spec.tsx
- libs/react/src/lib/form/buttonGroup/buttonGroup.test.tsx
- libs/react/src/lib/list/list.spec.tsx
- libs/react/src/lib/list/listItem.spec.tsx
- libs/react/src/lib/modal/modal.spec.tsx
- libs/react/src/lib/tabs/tabs.spec.tsx
> test: 💍 add missing tests

- libs/react/src/lib/form/form.spec.tsx
- libs/react/src/lib/form/form.stories.mdx
- libs/react/src/lib/form/formItems.tsx
- libs/react/src/lib/form/input/input.tsx
- libs/react/src/lib/form/radioButton/radioGroup.spec.tsx
- libs/react/src/lib/form/radioButton/radioGroup.tsx
- libs/react/src/lib/form/validateInput.spec.tsx
- libs/react/src/lib/form/validateInput.ts
> feat: 🎸 added radio-btn validation

- libs/chlorophyll/scss/tokens/_shame.scss
> fix: update default token value for font location

- apps/angular-lib-dev/src/app/dropdown/dropdown.component.html
- apps/angular-lib-dev/src/app/dropdown/dropdown.component.ts
- libs/angular/src/lib/dropdown/dropdown.component.ts
- libs/angular/src/lib/dropdown/dropdown.spec.ts
- libs/chlorophyll/scss/components/_index.scss
- libs/chlorophyll/scss/components/container/_index.scss
- libs/chlorophyll/scss/components/container/_mixins.scss
- libs/chlorophyll/scss/components/dropdown/_mixins.scss
- libs/chlorophyll/scss/components/dropdown/dropdown.stories.mdx
- libs/chlorophyll/scss/components/form/common/_mixins.scss
- libs/chlorophyll/scss/components/form/validation/_index.scss
- libs/extract/src/lib/dropdown/dropdown.spec.ts
- libs/extract/src/lib/dropdown/dropdown.ts
- libs/extract/src/lib/dropdown/index.ts
- libs/react/src/lib/dropdown/dropdown.spec.tsx
- libs/react/src/lib/dropdown/dropdown.tsx
* Body scroll lock when dropdown is open
* Toggle-button text overflow
* Listbox & modal max height
* Chevron blue color
* Use initial values to get correct styling for listbox before dropdown is created
* Toggle-button cursor
* Close button
> fix(dropdown): body-scroll-lock and styling

- libs/chlorophyll/scss/components/form/common/_mixins.scss
> fix(form): margin for form info in horizontal form

- libs/chlorophyll/scss/components/_shame.scss
- libs/chlorophyll/scss/components/button/_mixins.scss
- libs/chlorophyll/scss/components/dropdown/_mixins.scss
- libs/chlorophyll/scss/components/form/common/_mixins.scss
- libs/chlorophyll/scss/components/form/input/_mixins.scss
Small, Medium and Large should follow design library specifications and be responsive to root font size
closes #554
closes #130
> fix(chlorophyll): form component responsive sizes

- libs/angular/src/lib/badge/badge.component.scss
- libs/angular/src/lib/badge/badge.component.ts
- libs/angular/src/lib/badge/badge.stories.ts
- libs/angular/src/lib/badge/documentation.mdx
- libs/extract/src/lib/badge.ts
- libs/react/src/lib/badge/badge.tsx
Closes [badge #535](https://github.com/sebgroup/green/issues/535)
> Change badge styles according to Design Library

- libs/angular/.storybook/main.js
- libs/angular/.storybook/tsconfig.json
- libs/angular/stories/button/button.stories.ts
- libs/angular/stories/button/documentation.mdx
Simple example of how to use buttons in Green/Angular
> docs(angular): add button usage example

- libs/chlorophyll/scss/components/form/common/_mixins.scss
- libs/chlorophyll/scss/components/form/validation/_mixins.scss
Fix webkit and mozilla errors.
> Fix webkit moz errors

- libs/react/src/lib/form/button/button.stories.mdx
- libs/react/src/lib/form/button/button.tsx
Fixes https://github.com/sebgroup/green/issues/581
> feat: Button (React) - add disabled property

- apps/react-lib-dev/src/app/app.tsx
- libs/react/src/lib/stepper/stepper.tsx
Stepper couldn't update to 0 because of condition.
✅ Closes: 599
> fix: 🐛 Stepper can go to 0

- libs/chlorophyll/stories/introduction/Install.stories.mdx
Proxies could cause packages not to download. Clarified that you need to check for proxies in documentation.
✅ Closes: #580
> docs: ✏️ Proxy config clarification

- libs/angular/package.json
> feat: 🎸 allow angular 14

- libs/chlorophyll/scss/components/form/radio/_mixins.scss
- libs/chlorophyll/scss/components/form/radio/_tokens.scss
- libs/chlorophyll/scss/components/form/radio/radio.stories.mdx
- libs/chlorophyll/scss/components/form/validation/_mixins.scss
- libs/chlorophyll/scss/tokens/_shame.scss
- libs/chlorophyll/scss/tokens/_shape.scss
- libs/chlorophyll/scss/tokens/_typography.scss
aligning radio buttons with the latest design from figma
BREAKING CHANGE: 🧨 change to html structure for fieldset form groups. checkboxes and radios should be wrapped in a div
✅ Closes: #459
> feat: 🎸 radio button with latest figma design

- libs/chlorophyll/scss/components/form/radio/_tokens.scss
not good support for these yet in green so commenting them out
> fix: 🐛 removing darkmode tokens

- libs/chlorophyll/scss/components/form/checkbox/_mixins.scss
- libs/chlorophyll/scss/components/form/checkbox/checkbox.stories.mdx
> feat: 🎸 indeterminate checkbox

- libs/chlorophyll/scss/common/_focus.scss
- libs/chlorophyll/scss/components/close/_mixins.scss
- libs/chlorophyll/scss/tokens/_colors.scss
Wrong size and color on close button in dropdown
✅ Closes: 671
> fix: 🐛 close button size in dropdown

- libs/angular/src/lib/progress-circle/documentation.mdx
- libs/angular/src/lib/progress-circle/progress-circle.component.html
- libs/angular/src/lib/progress-circle/progress-circle.component.ts
- libs/angular/src/lib/progress-circle/progress-circle.module.ts
- libs/angular/src/lib/progress-circle/progress-circle.stories.ts
- libs/chlorophyll/scss/components/_index.scss
- libs/chlorophyll/scss/components/progress-circle/_functions.scss
- libs/chlorophyll/scss/components/progress-circle/_index.scss
- libs/chlorophyll/scss/components/progress-circle/_mixins.scss
- libs/extract/src/index.ts
- libs/extract/src/lib/progress-circle.ts
New Progress Circle component for Green Angular:
> feat: 🎸 new progress circle component for angular

- libs/angular/package.json
- libs/angular/src/lib/modal/documentation.mdx
- libs/angular/src/lib/modal/modal.component.spec.ts
- libs/angular/src/lib/modal/modal.component.ts
- libs/angular/src/lib/modal/modal.module.ts
- libs/angular/src/lib/modal/modal.stories.ts
- package.json
- yarn.lock
Added functionality to trap focus inside modal (Angular)
> feat: 🎸 Angular modal focus functionality

- libs/angular/src/lib/button/button.component.ts
- libs/angular/src/lib/button/button.stories.ts
- libs/chlorophyll/scss/components/button/_mixins.scss
- libs/chlorophyll/scss/components/button/button.stories.mdx
- libs/extract/src/lib/button.ts
- libs/react/src/lib/form/button/button.stories.mdx
- libs/react/src/lib/form/button/button.tsx
> feat: 🎸 add new large button size for jumbotrons/heroes

- .github/workflows/release-angular-charts.yml
- .github/workflows/release-angular.yml
- .github/workflows/release-charts.yml
- .github/workflows/release-chlorophyll.yml
- .github/workflows/release-extract.yml
- .github/workflows/release-react-charts.yml
- .github/workflows/release-react.yml
- libs/angular-charts/project.json
- libs/angular/project.json
- libs/charts/project.json
- libs/chlorophyll/project.json
- libs/extract/project.json
- libs/react-charts/project.json
- libs/react/project.json
- nx.json
Breaking up the release workflow into one for each package.
Dependancies will have to be handled manually in the beginning but as we learn more how packages are connected and what we can automate we can improve this.
When this is merged I will make a 1.0.0 release
> Seperate package releases

- libs/angular/src/lib/Get-started.stories.mdx
> chore: 🤖 angular release 1.0.0

- libs/react/src/lib/form/radioButton/radioGroup.spec.tsx
- libs/react/src/lib/form/radioButton/radioGroup.tsx
With valueSelected on RadioGroup you can now set the selected value of the RadioGroup programmatically.
> feat: 🎸 adding valueSelected to RadioGroup

- libs/chlorophyll/scss/components/select/_mixins.scss
> fix: 🐛 responsive click on select arrow

- libs/angular/src/lib/datepicker/datepicker.component.ts
> fix(angular): datepicker detect changed options

- libs/angular/src/lib/datepicker/datepicker.component.html
- libs/angular/src/lib/datepicker/datepicker.component.ts
> fix: datepicker rerender & ontouch

- libs/angular-charts/src/lib/chart/chart.stories.ts
- libs/angular-charts/src/lib/chart/ngg-chart.component.ts
- libs/charts/src/lib/billboard.spec.ts
- libs/charts/src/lib/billboard.ts
- libs/charts/src/lib/types.ts
> feat: 🎸 adding config options and removing custom x-axis

- libs/angular/src/lib/slider/documentation.mdx
- libs/angular/src/lib/slider/slider.component.html
- libs/angular/src/lib/slider/slider.component.ts
- libs/angular/src/lib/slider/slider.stories.ts
- libs/chlorophyll/scss/components/slider/_index.scss
> feat: 🎸 add input instruction and placeholder props to the component

- libs/chlorophyll/scss/components/form/common/_mixins.scss
> fix: 🐛 margin on form-item and form-group

- libs/angular/src/lib/progress-circle/documentation.mdx
- libs/angular/src/lib/progress-circle/progress-circle.component.html
- libs/angular/src/lib/progress-circle/progress-circle.component.ts
- libs/angular/src/lib/progress-circle/progress-circle.stories.ts
- libs/chlorophyll/scss/components/progress-circle/_index.scss
- libs/chlorophyll/scss/components/progress-circle/_mixins.scss
- libs/extract/src/lib/progress-circle.ts
> feat: 🎸 new progress circle disabled theme

- libs/chlorophyll/scss/common/_focus.scss
- libs/chlorophyll/scss/components/button/_index.scss
- libs/chlorophyll/scss/components/button/_mixins.scss
- libs/chlorophyll/scss/components/button/button.stories.mdx
Add styles corresponding to https://designlibrary.sebgroup.com/components/pattern-delete
closes #565
> feat(button): add `danger` variants

- libs/chlorophyll/scss/components/select/_mixins.scss
> fix: 🐛 truncating long options for select

- libs/chlorophyll/scss/components/link/_index.scss
- libs/chlorophyll/scss/components/link/_mixins.scss
- libs/chlorophyll/scss/components/link/link.stories.mdx
- libs/chlorophyll/scss/tokens/_shame.scss
This PR consist of these changes
> feat: 🎸 Add link variants: animated with arrow, icon on the left or right

- libs/charts/package.json
- libs/charts/src/lib/billboard.ts
- libs/charts/src/lib/types.ts
- libs/react-charts/src/lib/chart.stories.tsx
- libs/react-charts/src/lib/chart.tsx
- libs/react-charts/src/usecases/lighthouse-1.stories.mdx
- package.json
- yarn.lock
same issue with React as previously closed for Angular: #609
> fix: remove custom x-axis from `react-charts`

- libs/react/src/lib/form/input/input.spec.tsx
- libs/react/src/lib/form/input/input.tsx
- libs/react/src/lib/form/types.ts
- libs/react/src/lib/form/useInput.ts
> fix: 🐛 input controllable with value prop

- libs/angular/src/lib/Get-started.stories.mdx
> docs(angular): fix style import example

- apps/colors/project.json
- apps/colors/src/app/app.tsx
- apps/colors/src/components/Swatch.tsx
- apps/colors/src/index.html
- tsconfig.base.json
- yarn.lock
Add interactive editing to color pallets. This feature is meant as a development tool to help us fine tune the color pallet for the new design.
> feat(colors): make color pallets editable

- libs/chlorophyll/scss/components/form/checkbox/_mixins.scss
> fix(checkbox): animations & hover

- libs/react/src/index.ts
> fix(accordion): add missing export for accordion

- apps/react-lib-dev/src/app/app.tsx
- libs/react/src/lib/slider/slider.tsx
- libs/react/src/types/props/index.ts
> feat(slider): add clamping to min-max range

- libs/chlorophyll/scss/components/slider/_index.scss
- libs/chlorophyll/scss/components/slider/_mixins.scss
- libs/chlorophyll/scss/components/slider/slider.stories.mdx
- libs/react/src/lib/slider/slider.stories.mdx
- libs/react/src/lib/slider/slider.tsx
- libs/react/src/types/props/index.ts
> feat(slider): add styles for min max labels

- libs/extract/src/lib/dropdown/dropdown.ts
> fix(dropdown): listbox should have same width as button

- libs/angular-charts/package.json
- libs/angular/package.json
- libs/charts/package.json
- libs/chlorophyll/package.json
- libs/extract/package.json
- libs/react-charts/package.json
- libs/react/package.json
SEB generic packages should use a SEB generic author.
> chore: update authors

- libs/extract/src/lib/datepicker/datepicker.ts
- libs/react/src/lib/datepicker/datepicker.tsx
> fix(datepicker): broken month and year dropdowns

- libs/extract/src/lib/datepicker/datepicker.ts
- libs/react/src/lib/datepicker/datepicker.stories.mdx
- libs/react/src/lib/datepicker/datepicker.tsx
> fix(datepicker): hard coded label

- libs/chlorophyll/.storybook/main.js
- libs/chlorophyll/scss/components/slide-toggle/_mixins.scss
> Fix(slide-toggle): darker background and hover-back transition

- libs/chlorophyll/scss/components/list/_mixins.scss
> fix(value-list): added small spacing

- libs/chlorophyll/scss/components/form/input/_mixins.scss
- libs/chlorophyll/scss/components/form/input/input.stories.mdx
> fix(input): added small version

- libs/chlorophyll/scss/components/slide-toggle/_mixins.scss
This PR adds a border to the slide toggle track in dark mode, for improved contrast.
> fix(slide-toggle): dark mode border

- libs/angular/src/lib/slider/slider.component.html
- libs/chlorophyll/scss/components/slider/_mixins.scss
- libs/chlorophyll/scss/components/slider/slider.stories.mdx
- libs/react/src/lib/slider/slider.tsx
> fix(slider): mobile version, small input on desktop, added aria-lable

- libs/chlorophyll/scss/components/typography/typography.stories.mdx
- libs/chlorophyll/scss/tokens/_typography.scss
- libs/chlorophyll/src/tokens/typography.ts
Adjust heading font weights according to latest design library specifications:
Figma: [SEB Design System - Font Styles](https://www.figma.com/file/dX0HJ2MOaQyAOTziCD5fQ7/SEB-Design-System?node-id=20783%3A58371)
> Fix: typography

- libs/angular/src/lib/datepicker/datepicker.component.ts
> fix(datepicker): correctly reflect state after formGroup reset

- libs/angular/src/lib/modal/documentation.mdx
- libs/angular/src/lib/modal/index.ts
- libs/angular/src/lib/modal/modal-footer.directive.ts
- libs/angular/src/lib/modal/modal-header.directive.ts
- libs/angular/src/lib/modal/modal.component.html
- libs/angular/src/lib/modal/modal.component.spec.ts
- libs/angular/src/lib/modal/modal.component.ts
- libs/angular/src/lib/modal/modal.module.ts
- libs/angular/src/lib/modal/modal.stories.ts
Added functionality to customize header and footer in the modal component (angular) without any breaking changes. Also added the ability to hide header and footer.
> feat(angular): modal custom header

- libs/chlorophyll/scss/components/list/_index.scss
- libs/chlorophyll/scss/components/list/_mixins.scss
- libs/chlorophyll/scss/components/list/list.stories.mdx
> feat: 🎸 add support for black color check icons on check lists

- libs/chlorophyll/scss/components/link/_mixins.scss
> fix(links): links now have thicker underline on hover on all browsers

- libs/react/src/lib/select/select.stories.mdx
- libs/react/src/lib/select/select.tsx
adding a prop so the name attribute can be set on the select component
> fix(react): adding name attribute to select

- libs/chlorophyll/scss/components/slider/_mixins.scss
> fix(slider): remove mobile multi-row layout

- apps/core-lib-dev/src/app/app.element.ts
- libs/core/package.json
> fix(core): add dependencies to `package.json`

- apps/react-lib-dev/src/app/form.tsx
- libs/chlorophyll/scss/components/form/common/_mixins.scss
> fix(datepicker): label spacing

- libs/chlorophyll/scss/components/themes/_index.scss
> fix(border-color): use a lighter border in dark mode for better contrast

- libs/chlorophyll/stories/introduction/Install.stories.mdx
> docs(install): add links to storybooks

- libs/angular-charts/project.json
- libs/angular/project.json
- libs/charts/project.json
- libs/chlorophyll/project.json
- libs/core/project.json
- libs/extract/project.json
- libs/react-charts/project.json
- libs/react/project.json
- package.json
- yarn.lock
Looks like the upgrade to NX 16 messed some stuff up.
> ci: fix broken releases

- libs/core/src/components/dropdown/dropdown.stories.mdx
- libs/core/src/primitives/listbox/listbox.trans.styles.scss
> fix(listbox): add `overflow-y`

- libs/core/src/components/dropdown/dropdown.test.ts
- libs/core/src/components/dropdown/dropdown.ts
> feat(core-dropdown): add `searchFilter` delegate function

- libs/chlorophyll/scss/components/badge/_mixins.scss
- libs/chlorophyll/scss/components/badge/badge.stories.mdx
- libs/chlorophyll/scss/components/close/_mixins.scss
- libs/chlorophyll/scss/components/fonts/_index.scss
- libs/chlorophyll/scss/components/themes/_mixins.scss
- libs/chlorophyll/scss/components/utility/_colors.scss
- libs/chlorophyll/scss/tokens/_shame.scss
> fix(chlorophyll): text colour on success and font path

- libs/chlorophyll/scss/components/form/validation/_mixins.scss
> fix(form-group): horizontal layout overflows

- libs/angular/src/lib/badge/badge.stories.ts
- libs/angular/src/lib/badge/documentation.mdx
- libs/angular/src/lib/modal/documentation.mdx
- libs/chlorophyll/scss/components/badge/badge.stories.mdx
- libs/chlorophyll/scss/components/list/_mixins.scss
- libs/chlorophyll/scss/components/modal/_mixins.scss
- libs/chlorophyll/scss/components/modal/modal.stories.mdx
- libs/chlorophyll/scss/components/reset/mixins.scss
- libs/chlorophyll/scss/components/tabs-bar/_mixins.scss
- libs/chlorophyll/scss/components/tabs-bar/tabs.stories.mdx
- libs/chlorophyll/scss/components/typography/_index.scss
- libs/chlorophyll/scss/components/typography/typography.stories.mdx
- libs/chlorophyll/scss/tokens/_colors.scss
- libs/chlorophyll/scss/tokens/_grid.scss
- libs/react/src/lib/badge/badge.stories.mdx
This pull request contains many style updated of components making them align with Figma and Design Library.
Closes: #1058 #1057 #648 #561 #563
- Changed breakpoints to em
- Removing fixed font size on html element
> Component style sync

- libs/react/src/lib/in-page-wizard/inPageWizardStepCard.tsx
Edit button was not visible on mobile - it now is :)
> fix(react): in-page wizard edit button on mobile

- libs/react-charts/package.json
BREAKING CHANGES: updating dependencies to new major version
> chore(react-charts): updating dependencies

- libs/angular/src/lib/datepicker/documentation.mdx
- libs/extract/README.md
- libs/react/src/lib/datepicker/datepicker.tsx
This PR is mainly intended to trigger new major releases for Angular and React related to the new Datepicker.
> feat(datepicker): Major release for React and Angular

- libs/chlorophyll/README.md
This PR is intended to create a patch version bump to Chlorophyll, since 3.0.0 was blocked in NPM.
> fix(chlorophyll): update readme

- libs/core/src/components/datepicker/date-part-spinner.ts
- libs/core/src/components/datepicker/datepicker.test.ts
- libs/core/src/components/datepicker/datepicker.ts
- libs/core/src/utils/helpers/transitional-styles.ts
* Properly detect Constructed Stylesheet support
* fix keyboard entry constraints in Datepicker spinners
Closes #1174
> fix(core/datepicker): properly constrain length of keyboard input

- libs/core/src/components/datepicker/datepicker.test.ts
- libs/core/src/components/datepicker/datepicker.ts
- libs/core/src/primitives/calendar/_mixins.scss
- libs/core/src/primitives/calendar/calendar.test.ts
- libs/core/src/primitives/calendar/calendar.ts
> fix(core/datepicker): today highlight style & focus handling

- .changeset/thick-numbers-perform.md
- libs/core/src/components/datepicker/datepicker.trans.styles.scss
- libs/core/src/components/datepicker/datepicker.ts
- libs/core/src/primitives/calendar/_mixins.scss
- libs/core/src/primitives/calendar/calendar.ts
- libs/core/src/primitives/popover/popover.ts
> Datepicker updates

- .changeset/tasty-birds-lay.md
- libs/chlorophyll/scss/components/close/_mixins.scss
Closes https://github.com/sebgroup/green/issues/1214
> fix: Close icon color on touchscreen

- README.md
- libs/angular-charts/README.md
- libs/angular/README.md
- libs/chlorophyll/README.md
- libs/core/README.md
- libs/extract/README.md
- libs/react-charts/README.md
- libs/react/README.md
> docs(all): updated readmes

- .changeset/honest-bags-compete.md
- libs/core/src/components/datepicker/datepicker.ts
- libs/core/src/primitives/calendar/calendar.ts
> fix(core): datepicker changing value when changing month

- .changeset/weak-carrots-try.md
- libs/chlorophyll/scss/components/button/_mixins.scss
- libs/chlorophyll/scss/components/form/checkbox/_mixins.scss
- libs/chlorophyll/scss/components/form/checkbox/_tokens.scss
- libs/chlorophyll/scss/components/form/common/_mixins.scss
- libs/chlorophyll/scss/components/form/disabled.stories.mdx
- libs/chlorophyll/scss/components/form/radio/_mixins.scss
- libs/chlorophyll/scss/components/form/radio/_tokens.scss
- libs/chlorophyll/scss/tokens/_shame.scss
- libs/chlorophyll/stories/use cases/dark mode/disabled-form.stories.mdx
- improved contrast on disabled inputs
- fixed styling issue where radio and checkboxes looked clickable when disabled
> fix(chlorophyll): improving contrast on disabled text color

- .changeset/smooth-comics-bow.md
- libs/chlorophyll/scss/tokens/_colors.scss
Removing pallet from colours since is not in use
> #1293 - Remove pallet from colors

- .changeset/fresh-jeans-rescue.md
- libs/tokens/src/tokens/color/sys/accent.json
- libs/tokens/src/tokens/color/sys/container.json
- libs/tokens/src/tokens/color/sys/content.json
- libs/tokens/src/tokens/color/sys/stroke.json
- libs/tokens/style-dictionary.config.ts
- Added missing tokens
- moved container colors into container category
- split up figma files based on variable collections. 
Variablecollections are groups that contains variables in Figma and have a a specific set of modes like "COLOR" or "COLOR SCHEME" contains modes like "Light", "Dark", "Light high contrast", "Light high contrast" and how "DENSITY" contains modes like "Compact", "Standard" or "Spacious"
> Tokens fixes

- .changeset/large-humans-crash.md
- libs/chlorophyll/scss/components/list/_mixins.scss
Fixing issue with contrast in list styles
> Chlorophyll: fix contrast in list styles

- .github/ISSUE_TEMPLATE/bug_report.yml
Added: 
1. Core 
2. Fonts 
3. Tokens
> Bug Report template update

- .changeset/new-jeans-dream.md
- libs/chlorophyll/scss/components/themes/_mixins.scss
Update card border radius to match Figma
> Chlorophyll: Update card border radius

- .changeset/dirty-knives-invent.md
- libs/angular/src/lib/context-menu/context-menu.component.ts
- libs/angular/src/lib/datepicker/datepicker.component.ts
- libs/angular/src/lib/dropdown/dropdown.component.ts
- libs/angular/src/lib/grouped-list/grouped-list.docs.mdx
- libs/angular/src/lib/grouped-list/grouped-list.stories.ts
- libs/core/README.md
- libs/core/docs/code-splitting.md
- libs/react/src/lib/context-menu/context-menu.tsx
- libs/react/src/lib/datepicker/datepicker.tsx
- libs/react/src/lib/dropdown/dropdown.tsx
- libs/react/src/lib/grouped-list/grouped-list.ts
This PR fixes failing imports in React and Angular introduced by the previous release
> Fix import paths

- libs/angular/src/lib/Get-started.stories.mdx
- libs/chlorophyll/stories/introduction/Use.stories.mdx
- libs/react/src/introduction/use.stories.mdx
> Clarify docs on importing styles

- .changeset/angry-rules-fold.md
- libs/angular/src/lib/modal/modal.component.html
- libs/angular/src/lib/modal/modal.component.spec.ts
- libs/angular/src/lib/modal/modal.component.ts
- libs/angular/src/lib/modal/modal.stories.ts
Adding enter and leave animations for modals
No support for reduce motion. Since this is prone for a rewrite to WC I wont dive into that now.
> feat: angular modal animations

- libs/core/src/components/icon/icon.stories.ts
> Typo on icon

- .changeset/brown-masks-fail.md
- libs/core/src/components/dropdown/dropdown.trans.styles.scss
> Dropdown: Fix line-breaks in webkit

- .changeset/few-windows-raise.md
- libs/core/src/components/datepicker/datepicker.trans.styles.scss
- libs/core/src/components/datepicker/datepicker.ts
#1322
Also, switch to using `<gds-icon-*>` and `<gds-button>` internally where possible.
> Fix Datepicker incorrect change event

- .changeset/plenty-pants-destroy.md
- libs/core/src/components/datepicker/datepicker.ts
> Fix datepicker copy paste

- .changeset/blue-countries-reply.md
- .changeset/fluffy-pillows-bow.md
- .changeset/fuzzy-shoes-reply.md
- libs/core/src/components/datepicker/datepicker.ts
- libs/core/src/components/popover/popover.ts
This PR solves #1231 and #1418
> Datepicker fixes

- .changeset/thin-eagles-ring.md
- libs/chlorophyll/scss/components/table/_mixins.scss
- Update table chlorophyll styles to latest SEB design system [Figma](https://www.figma.com/design/dX0HJ2MOaQyAOTziCD5fQ7/SEB-Design-System?node-id=13012-61984&m=dev)
Previous:
Latest:
> refactor: 💡 update table styling according to SEB design system

- .changeset/lemon-jobs-heal.md
- README.md
- libs/react/src/lib/accordion/accordion-item.tsx
- libs/react/src/lib/accordion/accordion.spec.tsx
- libs/react/src/lib/accordion/accordion.stories.mdx
Added a support so that user can set accordions starting state as open or closed based on their needs.
> feat: added a support for accordion so that user can set accordions starting state as open or closed based on their needs.

- .changeset/old-pandas-invent.md
- libs/react/src/lib/accordion/accordion-item.tsx
- libs/react/src/lib/accordion/accordion.spec.tsx
- libs/react/src/lib/accordion/accordion.stories.mdx
- added support for custom accordion labels
- added scrolling for accordion items content
> feat: 🎸 support custom label for accordion

- .changeset/gorgeous-waves-fail.md
- libs/angular/src/lib/modal/modal.component.html
- libs/angular/src/lib/modal/modal.component.spec.ts
- libs/angular/src/lib/modal/modal.stories.ts
- libs/chlorophyll/scss/components/modal/_mixins.scss
- Updated storybooks
- Support for sizes in dialog modal
> Adding support for sizes in dialog

- .changeset/giant-peaches-grow.md
- libs/react/src/lib/form/iconButton/iconButton.tsx
fix: added title property in iconButton
> added title property

- libs/chlorophyll/scss/components/close/_mixins.scss
> moving sass declarations before nested rules

- .changeset/giant-ligers-occur.md
- .github/workflows/release-swift.yml
- libs/tokens/project.json
* Fix missing package.json for Tokens package
* Add previously omitted changeset to Chlorophyll
> Fix release issues

- .changeset/happy-colts-joke.md
- .changeset/witty-mirrors-march.md
- libs/core/src/components/popover/popover.styles.ts
- libs/core/src/primitives/listbox/listbox.styles.ts
- libs/core/src/primitives/listbox/option.trans.styles.scss
- libs/core/src/primitives/listbox/option.ts
And enable scroll in the 2023 version
> Fix missing checkmarks in Dropdown

- .changeset/quick-roses-greet.md
Add missing changeset to release green core
> Add changeset to release green-core

- .changeset/popular-cars-sip.md
- .changeset/serious-eagles-wink.md
- libs/core/src/components/dropdown/dropdown.ts
- libs/core/src/components/popover/popover.ts
> Some bug fixes for Dropdown

- .github/workflows/deploy-all-storybooks.yml
- libs/angular-charts/.storybook/designlibrary.json
- libs/angular-charts/project.json
- libs/angular/.storybook/designlibrary.json
- libs/angular/project.json
- libs/chlorophyll/.storybook/designlibrary.json
- libs/chlorophyll/project.json
- libs/react-charts/.storybook/designlibrary.json
- libs/react-charts/project.json
- libs/react/.storybook/designlibrary.json
- libs/react/project.json
This is a fix for the `delignlibrary.json` files that went missing after the upgrade to Storybook 7.
For now, these will just be static files that are copied to the output dir during build.
> Add back `designlibrary.json`

- .changeset/lucky-clocks-invent.md
- libs/chlorophyll/scss/components/pagination/_mixins.scss
- libs/chlorophyll/scss/components/pagination/pagination.mdx
> Pagination size fix

- .changeset/mean-pugs-shout.md
- .changeset/slimy-keys-repair.md
- libs/core/src/components/button/button.stories.ts
- libs/core/src/components/button/button.style.css
- libs/core/src/components/icon/icon.style.ts
- Remove `max-width` from button and update story.
- Remove `display: contents` from icons.
> Fix Button width

- .changeset/two-terms-confess.md
- libs/core/src/components/menu-button/menu-button.css
This is a small fix based on the feedback when looking at Menu Button on intranet and new seb.io update
> Fix Menu Button gap

- .changeset/famous-ducks-act.md
- libs/core/setup-jest.js
> Add additional ElementInternals mocks for Jest

- .changeset/sour-knives-judge.md
- libs/angular/src/lib/accordion/accordion-list-item.component.html
> fixing accordion heading

- .changeset/short-cameras-listen.md
- libs/chlorophyll/scss/components/modal/_mixins.scss
> Modal close min width fix

- apps/core-lib-dev/src/app/theme-page/theme-page.element.ts
- apps/core-lib-dev/src/components/expenses.ts
needs spacing adjustments from parent component i believe,
> expenses push

- .changeset/soft-ducks-battle.md
- libs/angular/project.json
- libs/chlorophyll/scss/components/form/group/_mixins.scss
- libs/react/src/lib/form/buttonGroup/buttonGroup.stories.tsx
- nx.json
Closes: #1177
Edit: Also have better storybook example for react
> Buttongroup now have visible text when hover focused ghost

- .changeset/strange-peas-drop.md
- libs/react/src/lib/dropdown/dropdown.tsx
Adding a prop that passes to core component to check if the field is mandatory or not.
> adding prop to hanve mandatory check

- .changeset/tiny-panthers-dream.md
- libs/core/src/components/badge/badge.stories.ts
- libs/core/src/components/badge/badge.ts
> Feat: Badge rounded border

- .changeset/calm-laws-rule.md
- libs/chlorophyll/scss/components/wizard/in-page/_mixins.scss
- libs/react/src/lib/in-page-wizard/inPageWizardStepCard.mdx
- libs/react/src/lib/in-page-wizard/inPageWizardStepCard.stories.tsx
Also better storybook example text variations.
Now follows the design better on the icon center alignment.
Closes: #1806
> Wizard button icon alignment fix

- libs/angular/src/v-angular/checkbox/checkbox.component.html
- libs/angular/src/v-angular/checkbox/checkbox.component.scss
- libs/angular/src/v-angular/checkbox/checkbox.component.ts
- libs/angular/src/v-angular/checkbox/checkbox.module.ts
- libs/angular/src/v-angular/checkbox/checkbox.stories.ts
- libs/angular/src/v-angular/radio/radio.component.html
- libs/angular/src/v-angular/radio/radio.component.scss
- libs/angular/src/v-angular/radio/radio.component.ts
- libs/angular/src/v-angular/radio/radio.module.ts
- libs/angular/src/v-angular/radio/radio.stories.ts
Alignment of error-icon and error text.
> Radio/Checkbox: Error message alignment

- .changeset/tricky-gorillas-trade.md
- libs/angular/src/lib/in-page-wizard/in-page-wizard-step-card.component.html
Update Icon to match Figma
Before:
After:
> Change Angular In page wizard icon

- .changeset/swift-pots-grab.md
- libs/angular/src/v-angular/account-number/README.md
- libs/angular/src/v-angular/account-number/account-number.pipe.ts
- libs/angular/src/v-angular/account-number/account-number.stories.ts
- libs/angular/src/v-angular/index.ts
- Added account-number folder to root-barrel.
- Changed pipe to be stand-alone
- Updated docs
- Updated story
> Account Number Pipe: Expose Pipe as Stand-Alone

- .changeset/young-rockets-drive.md
- apps/core-lib-benchmark/src/app/benches/context-menu.ts
- libs/core/src/components/context-menu/context-menu.test.ts
- libs/core/src/components/context-menu/context-menu.ts
1000 instances with transitional styles render time improved ~3x, mainly by making rendering of the popover conditional on whether it is open or not.
> Performance improvements for Context menu

- libs/angular/src/v-angular/datepicker/components/calendar/calendar.component.spec.ts
I'm disabling the `returns disabled for 'today'` test for now, since it seems to fail randomly depending on the current date.
> Disable flaky test

- .changeset/polite-cobras-sing.md
- libs/angular/src/lib/dropdown/dropdown.component.html
- libs/angular/src/lib/dropdown/dropdown.component.scss
> NggDropdown: Fix trigger overflow style

- .changeset/forty-cups-poke.md
- libs/tokens/src/tokens/color-v2/color.json
> Tokens: Fix typo on L2 content information

- .changeset/healthy-boats-dress.md
- .changeset/itchy-weeks-wonder.md
- .changeset/moody-doors-leave.md
- libs/core/src/components/card/card.component.ts
- libs/core/src/components/dialog/dialog.component.ts
- libs/core/src/components/dialog/dialog.stories.ts
- libs/core/src/components/dialog/dialog.styles.ts
- libs/core/src/components/div/div.component.ts
- libs/core/src/gds-element.ts
- libs/core/src/utils/decorators/style-expression-property.ts
- libs/core/src/utils/decorators/watch-media-query.ts
- libs/core/src/utils/global-styles.ts
- libs/core/src/utils/helpers/platform.ts
In this PR:
- Remove backdrop blur effect
- Add style expression properties for sizing
- Fix VoiceOver issue with the `open` prop
> Dialog updates

- .changeset/gorgeous-starfishes-shake.md
- libs/core/src/tokens.style.ts
Fix for tokens that went missing under certain conditions. Should also solve #2173
> Core: Fix missing base tokens

- .changeset/new-sloths-roll.md
- libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.html
- libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.scss
- Keyboard select dropdown with NVDA-open (show selected dropdown label instead of blank)
> V-Angular Dropdown/Typeahead: Keyboard select dropdown with nvda

- .changeset/beige-cycles-crash.md
- libs/core/src/components/popover/popover.component.ts
> Dropdown: fixing flicker when selecting in dropdown searchable

- .changeset/cuddly-rules-rest.md
- libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.scss
- libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.ts
- libs/angular/src/v-angular/dropdown/dropdown.component.html
- libs/angular/src/v-angular/dropdown/dropdown.component.scss
- libs/angular/src/v-angular/dropdown/typeahead/typeahead-dropdown-list/typeahead-dropdown-list.component.ts
- Added dynamic position to enable automatic placement of the dropdown above or below the input based on available viewport space.
- Dynamically adjust the dropdown list’s max-height to fit the available space when there is less space than default max-height
> V-Angular Dropdown: Improve dropdown dynamic positioning and height calculation

- .changeset/shaggy-colts-argue.md
- libs/angular/src/lib/dropdown/dropdown.component.ts
Optional DropdownOption interface value type addition
> feat: add ability to set dropdown option value type

- .changeset/silly-ducks-teach.md
- .changeset/spotty-doors-beam.md
- libs/core/src/components/button/button.stories.ts
- libs/core/src/components/button/button.styles.ts
- libs/core/src/components/card/card.component.ts
- libs/core/src/components/card/card.stories.ts
- libs/core/src/components/context-menu/context-menu.styles.ts
- libs/core/src/components/details/details.styles.ts
- libs/core/src/components/menu-button/menu-button.styles.ts
- libs/core/src/components/rich-text/rich-text.component.ts
- libs/core/src/components/segmented-control/segment/segment.styles.ts
- libs/core/src/components/segmented-control/segmented-control.styles.ts
- libs/core/src/components/spinner/spinner.component.ts
- libs/core/src/primitives/field-base/field-base.styles.ts
- libs/core/src/primitives/listbox/option.styles.ts
- libs/core/src/shared-styles/rbcb-toggle.style.ts
- libs/tokens/src/tokens/2023/state.dark.json
- libs/tokens/src/tokens/2023/state.light.json
- libs/tokens/src/tokens/2023/tokens.base.json
Aligning state & shadow variables with what exsists in Figma.
> State & Shadow variables update

- .changeset/tricky-ears-remain.md
Adds missing changeset from previous fonts update PR
> Trigger release of Core
