seb-oss/green

libs/chlorophyll/scss/common/_focus.scss

removes the `border-color` reset in the common focus mixin, the `initial` value resets value based on web specification and it forces components that uses the mixin to explicitly override them
closes #395

fix: remove border color reset on focus

---

libs/angular/src/lib/dropdown/dropdown.component.ts

@hjalmers @JohanObrink 
The angular dropdown popover in mobile is quickly visible at the bottom on page load (it transitions out) - because the classes are missing on the first render so it starts with default styles. Once angular binds the classes on the second render it transitions out. Of course these styles are normally applied from the first render so the transition isn't triggered. 
**The reason:** Angular evaluates bindings as a part of the component lifecycle (not during the template execution) - so if some code triggers a reflow in-between a render will occur before the bound classes are applied. 
One issue of this was caused by a usage of `.innerText` (triggers a reflow) of an element in the template - this is solved in the commit and I think textContent should be fine.
But …

fix(dropdown): popover transitions out on init

---

libs/react/src/lib/card/card.tsx

When the <p> tag is present, we we're seeing warnings in our console-log:
"Warning: validateDOMNesting(...): <div> cannot appear as a descendant of <p>."

Remove <p> tag wrapping {children} in Card

---

libs/chlorophyll/scss/components/use-green-scope/_index.scss
libs/chlorophyll/stories/use cases/mixing frameworks/use-green-in-shells.stories.mdx

When setting up use-green scope it was not possible to configure font path. Now you can do it by adding a config to the import of use-green-scope

fix: 🐛 Configurable font path when setting up use-green-scope

---

libs/react/src/lib/stepper/stepper.tsx

The Stepper got stuck in a infinite loop when changing state in parent
component in the onChange prop.

fix: 🐛 Stepper state loop with onChange

---

.storybook/addons/iframe-canvas-mode/manager.js
.storybook/manager.js
.storybook/preview.js

This PR adds a querystring param to Storybook, which customizes the layout so the Canvas with Controls panel can be embedded in an iframe.
Here's an example:
It's activated by adding `iframeCanvasMode=true` to the Storybook URL.

Feature: iFrame Canvas Mode

---

apps/react-lib-dev/src/app/app.tsx
libs/chlorophyll/scss/components/popover/_index.scss
libs/extract/src/lib/dropdown/defaultValues.ts

elements with the class popover gets removed by global scripts. prefixing the class with _ until the script is removed.
✅ Closes: #560

refactor: 💡 changing popover class due to IBP conflict

---

.storybook/addons/designlibrary/generate-json-preset.js
.storybook/main.js
libs/chlorophyll/scss/components/alert/alert.stories.mdx
libs/chlorophyll/scss/components/badge/badge.stories.mdx
libs/chlorophyll/scss/components/button/button.stories.mdx
libs/chlorophyll/scss/components/card/card.stories.mdx
libs/chlorophyll/scss/components/datepicker/datepicker.stories.mdx
libs/chlorophyll/scss/components/dropdown/dropdown.stories.mdx
libs/chlorophyll/scss/components/form/checkbox/checkbox.stories.mdx
libs/chlorophyll/scss/components/form/input/input.stories.mdx
libs/chlorophyll/scss/components/form/radio/radio.stories.mdx
libs/chlorophyll/scss/components/form/stepper/stepper.stories.mdx
libs/chlorophyll/scss/components/form/textarea/textarea.stories.mdx
libs/chlorophyll/scss/components/link/link.stories.mdx
libs/chlorophyll/scss/components/list/list.stories.mdx
libs/chlorophyll/scss/components/modal/modal.stories.mdx
libs/chlorophyll/scss/components/navbar/navbar.stories.mdx
libs/chlorophyll/scss/components/skeleton-loader/skeleton-loader.stories.mdx
libs/chlorophyll/scss/components/slide-toggle/slide-toggle.stories.mdx
libs/chlorophyll/scss/components/table/table.stories.mdx
libs/chlorophyll/scss/components/tabs-bar/tabs.stories.mdx
package.json
yarn.lock

This PR adds a Storybook preset addon which generates a json file similar to stories.json, but tailored for Design Library.
This will allow us to specify Design Library component IDs on stories, so they can be automatically matched to a component page in Dersign Library.
The component IDs are specified in the `parameters` metadata of a story:
```jsx
<Meta
title="Components/Alert"
parameters={{
componentIds: ['component-alertribbon']
}}
/>
```
Some stories may relate to several components in Design Library, so multiple IDs can be specified:
```jsx
<Meta
title="Components/Modal"
parameters={{ 
componentIds: [
'component-dialogue',
'component-foldout',
'component-slideout',
'component-slideup',
'component-takeover'
]
}}
/>
```
IDs can also be specified on a sub-story level:
```jsx
<Story …
```

feat(storybook): add preset addon for DL json

---

libs/charts/scss/mixins.scss

Red was seen as a negative color by users so it should not be used in charts

style: 💄 removing red from charts

---

libs/extract/src/lib/stepper/stepper.spec.ts
libs/extract/src/lib/stepper/stepper.ts
libs/react/src/lib/stepper/hook.ts
libs/react/src/lib/stepper/stepper.tsx

onChange should not be emitted when the stepper is created - and not when setting the value from a parent component (eg: when the component is used like a controlled input)

fix(stepper): only emit onChange on user events

---

libs/chlorophyll/scss/components/form/checkbox/_mixins.scss
libs/chlorophyll/scss/components/form/checkbox/_tokens.scss
libs/chlorophyll/scss/components/form/checkbox/checkbox.stories.mdx
libs/chlorophyll/scss/components/form/common/_mixins.scss
libs/chlorophyll/scss/components/form/validation/_mixins.scss
libs/chlorophyll/scss/tokens/_colors.scss

The hmtl structure and styling of fieldsets were not optimal. I added a div to wrap lables/checkboxes in fieldset, this way we can have more predictable sizing. Also updated line-heights and font-sizes to match design in Figma. Also fixed some problems with tokens being dark ones but should be light. Also improved focus visuals with :has
BREAKING CHANGE: 🧨 -Breaks fieldset styling since we need to add a div to to wrap the form items.

style: 💄 Checkbox, fieldset, forminfo and validation

---

libs/angular/src/lib/dropdown/dropdown.component.ts
libs/extract/src/lib/dropdown/dropdown.ts
libs/extract/src/lib/dropdown/reducers.spec.ts
libs/extract/src/lib/dropdown/reducers.ts
libs/extract/src/lib/dropdown/types.ts

reset field form control when user programatically formControl.reset() field and update touched state after user is leaving field
BREAKING CHANGE: - -
✅ Closes: 643
[issue](https://github.com/sebgroup/green/issues/643)

feat: 🎸 dropdown add formControl reset functionality

---

README.md

Uppercased commands doesn't work in all terminals.

Change SET to set in README

---

libs/chlorophyll/scss/components/form/checkbox/_mixins.scss

Checkbox icon is not rendering properly on low pixel density screens. Using transform scale makes it better.

fix: 🐛 rendering issues on low pixel density displays

---

libs/angular/src/lib/modal/modal.component.ts
libs/chlorophyll/scss/components/alert-ribbon/alert-ribbon.stories.mdx
libs/chlorophyll/scss/components/badge/badge.stories.mdx
libs/chlorophyll/scss/components/button/button.stories.mdx
libs/chlorophyll/scss/components/card/card.stories.mdx
libs/chlorophyll/scss/components/modal/_mixins.scss
libs/chlorophyll/scss/components/modal/modal.stories.mdx
libs/react/src/lib/alert/alert.tsx
libs/react/src/lib/badge/badge.tsx
libs/react/src/lib/card/card.stories.mdx
libs/react/src/lib/form/button/button.stories.mdx
libs/react/src/lib/modal/modal.tsx

Fixed usage of close button in alert, badge, button, card and modal.
**Issues left**
- Looks strange when you press the close button on badges and also the close button is barely visible on dark badges since its black.
- The alert component for react looks broken, so the placement of the close button is not correct.

fix: 🐛 Usage of close in alert, badge, button, card & modal

---

libs/react/src/lib/datepicker/datepicker.spec.tsx

New function created to add leading zeroes to month values to fix below failing unit test case:

test: 💍 fix failing unit test in react datepicker

---

libs/angular/src/lib/dropdown/documentation.mdx
libs/angular/src/lib/dropdown/dropdown.stories.ts
libs/extract/src/lib/dropdown/reducers.ts

When the user tries to reset the form, it will not work properly if the dropdown options value contain more than one field.
BREAKING CHANGE: 🧨 --
✅ Closes: #690

fix: 🐛 dropdown formControl reset functionality

---

libs/angular/src/lib/dropdown/dropdown.component.ts

Allow to change dropdown translation then language is changing
BREAKING CHANGE:  -
✅ Closes: -

fix: 🐛 not updated dropdown translations on texts input change fix

---

libs/chlorophyll/scss/components/slide-toggle/_mixins.scss

The transition being set directly in the mixin caused some awkward visual effects when using e.g. `visibility: hidden` on a parent element. Moving the transition styling to appear only on hover effect (which is the intended use of it), keeps the visual transition effect when needed, but does not give awkward visual effects when using `visibility:hidden`.
To reproduce:
- go to [storybook: slide-toggle](https://sebgroup.github.io/green/latest/chlorophyll/?path=/docs/components-slide-toggle--slide-toggle)
- open dev tools and apply `visibility:hidden;` on a parent element to the slide-toggle button
- watch how it disappears from the view with an awkward transition
The new code will only apply the transition when hovering and you can toggle the visibility of a parent element as much as you …

fix(slide-toggle): 🐛 move transition to hover

---

libs/chlorophyll/scss/components/form/input/_mixins.scss

Text input fields should have a regular text cursor on hover. Currently they have the `pointer` cursor type, which is typically associated with links or other interactive elements which can receive click actions.
Closes #323

Text inputs should not have the pointer (hand) cursor

---

libs/chlorophyll/scss/components/alert-ribbon/alert-ribbon.stories.mdx
libs/chlorophyll/scss/components/close/close.stories.mdx
libs/chlorophyll/scss/components/form/checkbox/checkbox.stories.mdx
libs/chlorophyll/scss/components/form/stepper/stepper.stories.mdx
libs/chlorophyll/scss/components/list/list.stories.mdx
libs/chlorophyll/scss/components/skeleton-loader/skeleton-loader.stories.mdx
libs/chlorophyll/scss/components/typography/typography.stories.mdx
libs/react/src/lib/badge/badge.stories.mdx

Some people were having issues which were caused by copy-pasted examples from Chlorophyll where React-style `className` was used instead of `class`.

docs(chlorophyll): change `className` to `class` in examples

---

libs/chlorophyll/scss/components/form/group/group.stories.mdx
libs/chlorophyll/scss/components/form/validation/_mixins.scss

[Form info of grouped elements have incorrect text color](https://github.com/sebgroup/green/issues/805):
Fix:

fix: 🐛 match form info color to feedback

---

libs/chlorophyll/scss/components/form/group/_mixins.scss

Issue [#816](https://github.com/sebgroup/green/issues/816):
Fix:

fix: 🐛 make static text fixed at the end of parent element

---

libs/react/src/lib/form/radioButton/radioGroup.stories.mdx

This PR adds improved documentation for the `RadioGroup` and `RadioButton` components in React

docs(radio-group): improve `RadioGroup` documentation for React

---

libs/react/src/lib/form/useInput.ts

This PR removes redundant state hooks in the React input component. These hooks cause unnecessary re-rendering of the component, which can make it awkward to use, and the `value` and `checked` states are already held in the native input element, so there's no need to duplicate them in state hooks.

fix(Input): remove redundant state hooks

---

libs/react/src/lib/slider/slider.spec.tsx
libs/react/src/lib/slider/slider.stories.mdx
libs/react/src/lib/slider/slider.tsx
libs/react/src/types/props/index.ts

Allows setting the value for Slider. Deprecates the `defaultValue` prop.

feat(slider): add value prop

---

libs/angular/src/lib/in-page-wizard/documentation.mdx
libs/angular/src/lib/in-page-wizard/in-page-wizard-step-card.component.html
libs/angular/src/lib/in-page-wizard/in-page-wizard-step-card.component.ts
libs/angular/src/lib/in-page-wizard/in-page-wizard-step-card.spec.ts
libs/angular/src/lib/in-page-wizard/in-page-wizard-step-card.stories.ts

Angular
Added missing event on edit button click. 
This is needed when content inside component needs to change state based on when edit button is clicked.
For example to an input that should be disabled when step card is not active. 
_No response_

feat: 🎸 Add handle edit click event emitter

---

libs/angular/src/lib/in-page-wizard/in-page-wizard-step-card.component.ts

Add Missing Output decorator to in-page wizard step card

fix: 🐛 Missing Output decorator to wizard step card

---

libs/angular/src/lib/dropdown/dropdown-button.directive.ts
libs/angular/src/lib/dropdown/dropdown.component.html
libs/angular/src/lib/dropdown/dropdown.component.ts
libs/angular/src/lib/dropdown/dropdown.module.ts
libs/angular/src/lib/dropdown/dropdown.spec.ts
libs/angular/src/lib/dropdown/dropdown.stories.ts
libs/angular/src/lib/dropdown/index.ts
libs/react/src/lib/dropdown/dropdown.tsx

This PR adds the option of using a custom layout in the dropdown button, similar to how you can currently use custom layouts for the options in the popover.
Closes #834

feat(dropdown): allow custom template for dropdown button

---

apps/react-lib-dev/src/app/app.tsx
libs/react/src/lib/slider/slider.tsx
libs/react/src/types/props/index.ts

Allow setting `undefined` value on the React slider, both programatically and through the input fields.
Closes #865

fix(slider): allow `undefined` values

---

libs/react/src/lib/slider/slider.spec.tsx
libs/react/src/lib/slider/slider.tsx
libs/react/src/types/props/index.ts

Also defer clamping of textbox value until focus moves away from the field or enter is pressed.
The slider will now only emit number values. If the user empties the text input field, the slider will emit its `min`-value (0 by default) through the `onChange`-callback.

fix(slider): emit `min` value when setting textbox to empty string

---

libs/chlorophyll/scss/components/button/_index.scss
libs/react/src/lib/form/iconButton/iconButton.tsx

The type attribute was missing from the IconButton, meaning if the button was used inside a `<form>`, it would [act as a submit button by default](https://stackoverflow.com/a/9824845/12416767). This meant that the expandableInfo button would trigger submission of a form, instead of just toggling the expandable info.
Adding it as a optional property, which defaults to `button` not to cause any breaking changes.

fix(icon-button): add missing type

---

libs/chlorophyll/scss/components/list/_mixins.scss
libs/chlorophyll/scss/components/list/list.stories.mdx

#877
In vale lists and list groups: Removed inverted class, and inverted all font weights on label and value - as the Figma sketch. Also changed header to normal weight and size 14px (from bolder and smaller).

fix: lists font wight and size

---

libs/angular/src/lib/context-menu/context-menu.component.html
libs/angular/src/lib/context-menu/context-menu.component.ts
libs/chlorophyll/scss/components/context-menu/_index.scss

Added markForCheck due to angular change detection not caching changes on scroll and improved css
BREAKING CHANGE: 🧨 -
✅ Closes: -

fix: 🐛 Context menu on scroll markForCheck and css fixes

---

libs/react/src/lib/tabs/tabs.spec.tsx
libs/react/src/lib/tabs/tabs.stories.mdx
libs/react/src/lib/tabs/tabs.tsx

Currently tabs only do not allow any content other than text. Second issue, the tab content and tab title are always equal. Now the tabs component allows adding tab children  components with any type of content
BREAKING CHANGE: 🧨 Tabs component now takes Tab child components as children.
✅ Closes:  #373

feat: 🎸 components can be added as tab content

---

libs/react/src/lib/tabs/tabs.spec.tsx
libs/react/src/lib/tabs/tabs.stories.mdx
libs/react/src/lib/tabs/tabs.tsx

When tabs have components making network calls or any heavy processing, it might be ideal to delay this processing until the user has selected that tab. In most cases with tabs, users will not be clicking aroound eveyry tab all the time and so loading such content creates unnecessary overhead
BREAKING CHANGE: 🧨 None
✅ Closes: #904

perf: ⚡️ only renders tab content when tab is selected

---

apps/react-lib-dev/src/app/app.tsx
apps/react-lib-dev/src/app/form.tsx
libs/chlorophyll/scss/components/link/_index.scss
libs/chlorophyll/scss/components/link/_mixins.scss
libs/react/src/lib/form/input/input.tsx
libs/react/src/lib/form/types.ts
libs/react/src/lib/formItem/formItem.stories.mdx
libs/react/src/lib/formItem/formItem.tsx

This Pull Request changes the `expandableInfo` field on Input components to accept any React node instead of only strings. This means that any React rendered markup will be allowed in the field. Useful for adding links for example. Use with care!
Actually, this was already possible when not using Typescript, since the only difference is that the *type* of the prop has changed from `string` to `React.ReactNode`.

feat(expandable-form-info): allow custom expandable content

---

libs/angular/src/lib/dropdown/documentation.mdx
libs/angular/src/lib/dropdown/dropdown.component.ts
libs/extract/src/lib/dropdown/dropdown.ts

There is a case where we need the dropdown options to be fixed at the top and not flip to the bottom (flipping to the bottom _cuts_ the dropdown options below):
Add a new attribute to accept whether the dropdown options placement should be fixed either at the top or the bottom.
i.e., passing "top-start" would fix the options at the top and disable the flipping:

feat: 🎸 new input to set fixed placment of dropdown options

---

libs/extract/src/lib/dropdown/reducers.ts

fix dropdown options then values is numeric starting from 0 which is falsy value, and currently prevents optio nvalue to be selected
BREAKING CHANGE:  -
✅ Closes: -

fix(dropdown): don't treat `0` as a falsy option value

---

libs/react/src/lib/form/formItems.spec.tsx
libs/react/src/lib/form/formItems.tsx

provide an alternative method for form context consumer to handle input change event in addition to the existing of `onFormSubmit` handler that is only trigger upon form submission

fix: 🐛 add onchange support to form items component

---

libs/chlorophyll/scss/components/themes/_mixins.scss
libs/chlorophyll/scss/tokens/_shame.scss

This PR increases the default `z-index` for Dropdown popover, so that it doesn't get hidden by the fixed header in some shells
Closes #955

fix(dropdown): increase default z-index of popover

---

libs/angular/src/lib/context-menu/context-menu.component.html
libs/angular/src/lib/context-menu/context-menu.stories.ts
libs/angular/src/lib/context-menu/documentation.mdx
libs/chlorophyll/scss/components/context-menu/_index.scss
libs/chlorophyll/scss/components/context-menu/_mixins.scss

When context menu was put in a parent HTML element, it was displayed in a wrong position due to top and left coordinates being calculated from the whole window, not from parent coordinate system. This change introduces an overlay in order to mitigate the issue in the simplest possible manner. The solution was inspired by material angular library tooltip component implementation.
BREAKING CHANGE: 🧨 -
✅ Closes: -

fix: 🐛 fix context menu position in relative parent

---

libs/angular/src/lib/context-menu/context-menu.component.ts

Due to the previous fix for x and y positions (adding an overlay) it is no longer needed to add scroll offset to the context menu y position.
BREAKING CHANGE: 🧨 -
✅ Closes: -

fix: 🐛 wrong calculation of y position for context menu

---

libs/chlorophyll/scss/components/reset/mixins.scss
libs/chlorophyll/scss/components/reset/reset.scss

The current fixed rem based unit cause issues in situations where font-size is enlarged.

fix(typography): switch back to unitless `line-height` for body

---

libs/extract/src/lib/form.ts
libs/react/src/lib/form/radioButton/radioGroup.stories.mdx
libs/react/src/lib/form/radioButton/radioGroup.tsx
libs/react/src/lib/form/types.ts
libs/react/src/lib/formItem/formItem.tsx

Extracting properties to its own interface to ensure consistency of this functionality. RadioGroup and Inputs had different interfaces for expandable info props. They should now extend the IExpandableInformation.

fix(react): fixed radio group prop type expandableInfo

---

libs/angular/src/lib/context-menu/context-menu.component.ts
libs/angular/src/lib/context-menu/context-menu.constants.ts

When zooming in / out the component does not reset it's position to (0; 0), hence when no width (only max-width) is specified the initial boundary condition on how to display it when it is close to the border of the container does not fully suffice and produce incorrect dynamic width (open and close differs in the context menu width too)
BREAKING CHANGE: 🧨 -
✅ Closes: -

fix: 🐛 wrong position after zoom-in due to cached position

---

libs/angular/src/lib/modal/documentation.mdx
libs/angular/src/lib/modal/modal.component.ts
libs/angular/src/lib/modal/modal.stories.ts

Scrolling inside a modal (angular) on iOS devices didn't work. By allowing touchmove on elements inside the modal, solved the scrolling issue on iOS devices.
**Other**
- Typos in the modal (angular) documentation.
- Issue with having trapFocus enabled on all the modal (angular) examples in Firefox.

fix: Angular modal scroll iOS

---

apps/react-lib-dev/src/app/form.tsx
libs/chlorophyll/scss/components/form/common/_mixins.scss
libs/extract/src/lib/form.ts
libs/react/src/lib/form/iconButton/iconButton.tsx
libs/react/src/lib/form/input/input.tsx
libs/react/src/lib/form/radioButton/radioGroup.tsx
libs/react/src/lib/formItem/formItem.tsx

Adding the possibility to pass a react node to the information label. added some overriding temporary styling since it clashed with old generated styling based on key words.
Also extracted the label and label information types to it's own interface.
This was requested by the loan team.

feat(react): information label can now be react node

---

.github/workflows/release.yml
libs/core/project.json
package.json

Suspecting that the publish target fails because I renamed the default build target to `build-src`. I think that causes the publish target to be unable to find the `outputPath` field. Let's see if this fixes it!

fix(core): break out to separate build command

---

.github/workflows/release.yml
libs/core/project.json
package.json

Apparently running the build as a post-target of `version-and-release` did not work. For some reason the output folder is deleted before the next post target (publish) gets to run.
The main issue is that NX has no way of specifying an action that runs *after* a given target, and `ngx-deploy-npm` is hard-coded to use the `build` target. Green Core needs a few post-processing steps to run after the build, so we need to try and coerce `ngx-deploy-npm` to call another target than the actual `build` target.

fix(core): attempt to fix build config

---

libs/chlorophyll/scss/components/wizard/in-page/_mixins.scss
libs/chlorophyll/scss/components/wizard/in-page/in-page-wizard.stories.mdx

Closes: [#922](https://github.com/sebgroup/green/issues/922)

fix: 🐛 edit button on mobile view

---

apps/core-lib-dev/project.json
libs/core/project.json
libs/core/src/components/dropdown/dropdown.stories.mdx
libs/core/src/components/dropdown/dropdown.test.ts
libs/core/src/components/dropdown/dropdown.trans.styles.scss
libs/core/src/components/dropdown/dropdown.ts
libs/core/src/primitives/listbox/option.trans.styles.scss
libs/core/src/primitives/popover/popover.styles.ts
libs/core/src/primitives/popover/popover.trans.styles.scss
libs/core/src/primitives/popover/popover.ts
libs/core/src/utils/decorators/index.ts
libs/core/src/utils/decorators/watch-media-query.ts

Related: #862
This PR corrects the mobile layout of the popover and adds a backdrop.
Since the mobile version is designed to work as a modal, I figured that the native modal `<dialog>` would be suitable here. It also gives us access to the `:backdrop` pseudo element, and makes use of the `#top-layer` stacking context.
A caveat is that it makes the view structure of the popover different in mobile view, meaning that we have to rely on media query events to update the view accordingly, which feels a bit "hacky". But since it is a small and simple component (the `gds-popover`), I think we can live with it.
Other options that could simplify it would be:
* Use the modal approach for larger (desktop) view as well (not visually, only semantically). This would make the rest of the page …

fix(dropdown): fix mobile view and add backdrop

---

.storybook/main.js
libs/angular-charts/.storybook/preview.js
libs/angular-charts/.storybook/preview.scss
libs/angular-charts/src/lib/chart/chart.stories.ts
libs/charts/src/lib/billboard.ts
libs/charts/src/lib/types.ts
libs/react-charts/.storybook/preview.scss
libs/react-charts/src/lib/chart.stories.tsx
package.json
yarn.lock

You can now pass a [color object](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.color) in the styles object in settings for the chart.
This makes it possible to override the default theme where needed.

feat(charts): custom colours

---

libs/angular/src/lib/slider/slider.component.html
libs/angular/src/lib/slider/slider.component.ts
libs/react/src/lib/slider/slider.spec.tsx
libs/react/src/lib/slider/slider.tsx
libs/react/src/types/props/index.ts

The default keyboard for `<input type='number'>` on mobile devices is not always fitting for the Slider component. By default, iOS shows a layout with a row of numbers on top and then a collection of special characters below, and in this case the desired layout is the pure numerical keyboard.
This PR also adds forwarding of the [`enterkeyhint`](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint) attribute to the input field.
Closes #1047

feat(slider): change to a text input with `inputmode='numeric'`

---

apps/react-lib-dev/src/app/alert-ribbons.tsx
apps/react-lib-dev/src/app/app.tsx
libs/react/src/lib/alert-ribbon/alert-ribbon.tsx

Hi! Misael from team ToConsume on SEB.
Noticed that an extra margin was added to the alert ribbon when no header was passed, this due to an empty header div with style being added that had a margin right.
I propose to not render the header instead if it is empty. I have not been able to test this code so please try it out before merging it in.
Best regards Misael

fix(alert-ribbon): don't render empty header

---

libs/chlorophyll/scss/components/use-green-scope/_index.scss
libs/chlorophyll/scss/tokens/_components.scss

radio/checkbox/filter styles are added outside of the .use-green scope. 
@use '...tokens/component' causes its styles to be imported. Only the tokens should be imported.

fix(chlorophyll): only import tokens in use-green-scope

---

libs/react/src/lib/dropdown/dropdown.stories.mdx
libs/react/src/lib/dropdown/dropdown.tsx

The wrapper will now simply forward `value` to the underlying component, and value will correspond to the `[useValue]` field in the options object.
Closes #1090

fix(react/dropdown): simplify how the React wrapper handles state

---

libs/charts/src/lib/billboard.spec.ts
libs/charts/src/lib/billboard.ts
libs/charts/src/lib/types.ts

Align the tooltipNumberFormat function with the format function in billboard.js. 
Also allow it to override the formatting for charts with ratio. 
The current percentage is not always correct (adds a lot of decimals even for numbers that javascript can divide correctly. Seems like the ratio value is calculated by the angle of the barchart pies rather than the actual values in the underlaying implementation - superwierd). Therefor also limiting the default to 2 decimals
Closes #687

feat(charts): add percentage formatting to tooltip

---

libs/core/src/generated/locales/sv.ts
libs/core/src/primitives/popover/popover.ts
libs/core/xliff/sv.xlf

This adds a missing `aria-label` to the close button in popovers. Only affects mobile viewport.

fix(dropdown): add missing label to close button

---

libs/chlorophyll/scss/tokens/_shame.scss

Turns out that this path is not relative to the project, but rather to the `.scss` file in the `@sebgroup/fonts` package. In other words, the previous default path was the correct one to use.

fix(fonts): revert path change

---

libs/react/src/lib/form/group/group.stories.mdx
libs/react/src/lib/form/group/group.tsx

Form groups that should have focus on the whole group now requires the `group-focus` class. There was no way to set this in the React component.
Now you can do this, as well as pass your own classes to the group if needed.

feat(react): groupFocus and className props

---

libs/angular/src/lib/dropdown/dropdown.component.html
libs/angular/src/lib/dropdown/dropdown.component.scss
libs/angular/src/lib/dropdown/dropdown.component.ts
libs/core/src/components/dropdown/dropdown.trans.styles.scss

When the content does not fit inside the space of the trigger, it should cut off with ellipsis instead of breaking to a new line. This was the default behaviour in the old version, so this PR fixes some incompatibilities caused by the upgrade.
This behavior can still be overridden with a custom trigger if a multi-line dropdown is required.

fix(dropdown): hidden overflow with ellipsis by default

---

libs/core/src/primitives/listbox/listbox.ts
libs/core/src/primitives/menu/menu-item.ts
libs/core/src/primitives/menu/menu.ts

The absolute paths works within the monorepo and in the tests, but fails in external use.

fix(core/context-menu): use the correct relative paths in imports

---

apps/core-lib-dev/project.json
libs/core/src/primitives/popover/popover.trans.styles.scss
libs/core/src/primitives/popover/popover.ts

This PR fixes incorrect positioning in the dropdown/context menu popover in mobile views.
It also adds a height adjustment when a virtual keyboard is present, to better accommodate dropdown with search.

fix(core/popover): positioning regression in mobile views

---

libs/angular/src/lib/slider/slider.component.ts

update slider track background when input min and max has changed, so it follows the "thumb" value:

fix: 🐛 update track background when min and max values change

---

libs/core/src/components/dropdown/dropdown.stories.mdx
libs/core/src/components/dropdown/dropdown.styles.ts
libs/core/src/components/dropdown/dropdown.test.ts
libs/core/src/components/dropdown/dropdown.ts
libs/core/src/primitives/popover/popover.styles.ts
libs/core/src/primitives/popover/popover.trans.styles.scss
libs/core/src/primitives/popover/popover.ts

This options forces the popover to sync its with to the trigger button, even if some options are wider. When enabled, option text that is wider than the trigger will wrap by default.

feat(core/dropdown): add `syncPopoverWidth` option

---

apps/react-lib-dev/src/app/form.tsx
libs/chlorophyll/scss/components/form/stepper/_mixins.scss
libs/extract/src/lib/stepper/stepper.ts
libs/react/src/lib/stepper/stepper.spec.tsx
libs/react/src/lib/stepper/stepper.stories.mdx
libs/react/src/lib/stepper/stepper.tsx

This PR refactors the Stepper to work as a purely controlled component.
BREAKING CHANGES:
* `value` is now *only* owned by host application. This means `onIncrease` and `onDecrease` have to be implemented for the stepper to work.
* `onChange` now takes a `ChangeEvent<HTMLInputElement>` as param.
* These props have been removed:
* `step`
* `min`
* `max`

fix(react/stepper): convert to pure controlled component

---

libs/chlorophyll/scss/tokens/_typography.scss
libs/chlorophyll/src/tokens/typography.ts

Font weight for H5 and H6 should be medium according to Figma spec
Figma: [SEB Design System - Font Styles](https://www.figma.com/file/dX0HJ2MOaQyAOTziCD5fQ7/SEB-Design-System?node-id=20783%3A58371)
✅ Closes: #1172

fix: 🐛 Change font weight for H5 and H6 

---

.changeset/nasty-mice-study.md
libs/angular/src/lib/datepicker/datepicker.component.ts
libs/angular/src/lib/dropdown/dropdown.component.ts

fix for control.reset() not updating ui value, similar issue also likely with patch, setValue
BREAKING CHANGE:  -
✅ Closes: #1206
easier to reproduce in fresh form with formGroup similar to
```
testForm = new FormGroup({
country: new FormControl(),
country2: new FormControl(),
});
options = [
{
label: 'Sweden',
value: 'sweden',
},
{
label: 'Denmark',
value: 'denmark',
},
{
label: 'Finland',
value: 'Finland',
},
];
public test() {
this.testForm.reset();
}
```
```
<form *ngIf="testForm" [formGroup]="testForm">
<div class="form-group">
{{ testForm.controls.country.value | json }}
<ngg-datepicker
label="history-date-to"
class="flex-grow"
formControlName="country"
/>
{{ testForm.controls.country2.value | json }}
<ngg-dropdown label="Country" [options]="options" formControlName="country2"> …
```

fix: 🐛 update visible value when Dropdown/Datepicker formGroup changed programatically

---

.changeset/five-buckets-sleep.md
libs/core/src/components/datepicker/datepicker.test.ts
libs/core/src/components/datepicker/datepicker.ts

Currently, stepping in the calendar changes the value and emits `change` events. This PR changes this behaviour so that it instead emits `input` events, until the value is committed by clicking on a date, pressing enter or by clicking outside to close. The `change` event is only emitted when the value is considered committed. Esc aborts by reverting to the value the Datepicker had when the calendar was opened.
This change is made to closer match the native `<input type="date">`

Datepicker input event when stepping in calendar

---

.changeset/stale-chairs-drum.md
libs/react/src/lib/dropdown/dropdown.stories.mdx
libs/react/src/lib/dropdown/dropdown.tsx

the dropdown in react should select falsy values like "", 0, null, undefined instead of ignoring them
✅ Closes: #1225

fix: 🐛 the dropdown in react should select falsy values

---

.changeset/honest-bags-doubt.md
apps/react-lib-dev/src/app/form.tsx
libs/angular/.storybook/preview.js
libs/angular/src/lib/datepicker/datepicker.component.html
libs/angular/src/lib/datepicker/datepicker.component.ts
libs/angular/src/lib/datepicker/datepicker.stories.ts
libs/angular/src/lib/datepicker/documentation.mdx
libs/core/src/components/datepicker/datepicker.stories.mdx
libs/core/src/components/datepicker/datepicker.test.ts
libs/core/src/components/datepicker/datepicker.ts
libs/core/src/primitives/calendar/calendar.ts
libs/react/src/lib/datepicker/datepicker.stories.mdx
libs/react/src/lib/datepicker/datepicker.tsx

**Datepicker:** Added support for disabling dates
- `disabled-weekends` will disable all weekend days in the calendar view
- `disabled-dates` allows to specify an array of dates that should be disabled in the calendar view
Closes #615

Datepicker: Add support for disabling dates

---

.changeset/little-crabs-cry.md
libs/chlorophyll/scss/components/dropdown/_mixins.scss
libs/chlorophyll/scss/components/popover/_mixins.scss
libs/core/src/components/datepicker/datepicker.trans.styles.scss
libs/core/src/components/dropdown/dropdown.trans.styles.scss
libs/core/src/primitives/calendar/_mixins.scss
libs/core/src/primitives/listbox/option.trans.styles.scss
libs/core/src/primitives/popover/popover.trans.styles.scss

**Note:** Some gray tones will be slightly incorrect now, compared to Figma,, because only the older set of gray tokens in Chlorophyll have dark mode configured, and I reverted to using those tokens now in this PR.
The tokens (especially grey values) needs to be synced and consolidated. But that is outside the scope of this PR.
**Note 2:** To check it out in Storybook, use the React one. It is currently the only one where dark mode can be selected and works properly :)

Fix broken dark mode for Datepicker and Dropdown

---

.changeset/shiny-bulldogs-dream.md
libs/core/src/components/datepicker/datepicker.test.ts
libs/core/src/components/dropdown/dropdown.ts

Dropdown: Only `undefined` should be considered as "no value"

---

.changeset/green-otters-work.md
libs/core/src/components/datepicker/datepicker.test.ts
libs/core/src/components/datepicker/datepicker.ts

According to UXW guidelines, dateformat should be in `YYYY-MM-DD`.

Changing placeholder datepicker format

---

.changeset/lucky-onions-hunt.md
libs/angular/src/lib/modal/modal.component.html

Updated slideout modal sizing in Angular to match design library
closes #[1263](https://github.com/sebgroup/green/issues/1263)

fix(angular/modals): slideout sizing

---

.changeset/real-poets-sparkle.md
.storybook/storybook-overrides.scss
libs/core/src/components/grouped-list/grouped-list.stories.mdx
libs/react/src/lib/list/valueList.stories.mdx
libs/react/src/lib/list/valueList.tsx

This PR adds an additional example to the Grouped list component, and marks the old `ValueList` component in React as deprecated.

Deprecate `ValueList` and update Grouped List examples

---

libs/core/src/components/grid/grid.stories.mdx

Very minor change a mistake on the grid example when using auto columns and columns combined.
Good catch @daggelito02

Fix: Typo Grid — #1298

---

.changeset/light-eels-compare.md
libs/core/src/components/grid/grid.stories.css
libs/core/src/components/grid/grid.stories.mdx
libs/core/src/components/grid/grid.style.css.ts
libs/core/src/components/grid/grid.ts

Add a new `row-gap` attribute to control the vertical axis of the gap. 
Has the exact same functionality as the default `gap` attribute. 
Additionally updated documentation to clarify sizes and breakpoints. 
Brought back breakpoints on all settings to avoid conflicts and misconfigurations.

Add Grid `row-gap` attribute

---

.changeset/mean-foxes-shout.md
libs/core/src/components/icon/icon.ts

`gds-icon` was using the wrong custom element decorator, causing it to register unscoped.

Fix `gds-icon` element scoping

---

.changeset/honest-actors-do.md
libs/core/src/components/grid/grid.style.css.ts

This is a minor fix for Safari where it would not get properly the initial count as zero and then it caused the auto columns to stop working entirely!

Add property for columns to fix init count on safari

---

.storybook/addons/designlibrary/generate-json-preset.js

This had stopped working because the newer version of Globby does not use commonjs modules.

Fix regression in building `designlibrary.json`

---

libs/tokens/project.json

I did create a new command to copy readme separately as yo use the assets apparently you should be using one of the executors that supports `assets` option.

Lib Tokens copy readme

---

.changeset/light-dots-sleep.md
libs/chlorophyll/scss/components/accordion/_mixins.scss

This PR reverts gray scale variables in Accordion to the older `--grey-xxx`, since these have working dark mode equivalents. This is a temporary fix until we have proper dark mode tokens in place.

Fix Accordion dark mode

---

.changeset/lucky-weeks-cross.md

Due to previous merge issues, 3.6.1 had already been published, so we need to bump it again.

Republish angular

---

.changeset/soft-moons-shop.md
libs/core/src/components/button/button.stories.ts
libs/core/src/components/button/button.style.css
libs/core/src/components/button/button.test.ts
libs/core/src/components/button/button.trans.styles.scss
libs/core/src/components/button/button.ts

Add support for links styled as buttons:
When an href attribute is set on gds-button the internal component renders an `<a> `instead of `<button>`.

feat(core): button link

---

.changeset/stupid-olives-deliver.md
libs/core/src/primitives/calendar/calendar.test.ts
libs/core/src/primitives/calendar/calendar.ts

Fix issue where the wrong month could be rendered in the calendar, if focused day number was outside the selected month (for example if 30th is focused and February was selected)
#1412

Fix Datepicker/Calendar rendering incorrect month in some cases

---

.changeset/nine-pears-remember.md
libs/core/src/components/popover/popover.ts

Fixes an issue where voiceover puts the focus on the close-button instead of the first option.
#1294

Fix dropdown focus issue in VoiceOver iOS

---

.changeset/real-cats-provide.md
libs/angular/src/lib/dropdown/dropdown.component.ts

if dropdown has  no selected values,  when changing text value visibleValue is calculated according to previous texts, and previous placeholder value displayed. 
To reproduce:
not select options ->change text input, -> old select placeholder displayed,  - forgot about this case in previous pr.

fix: 🐛 visible placeholder value then text changes and nothing selected

---

.changeset/brown-readers-cross.md
.changeset/famous-pens-marry.md
.changeset/strong-ants-confess.md
.changeset/wicked-files-provide.md
libs/core/src/components/calendar/calendar.stories.ts
libs/core/src/components/calendar/calendar.test.ts
libs/core/src/components/calendar/calendar.ts

This PR adds the following features to `<gds-calendar>`:
- Option to hide day name header
- Option to hide days outside of displayed month
- Option to cancel `gds-date-focused` event
- Ability to customize `aria-label` for dates through a template function

Additional view options for Calendar

---

.changeset/lazy-pumas-try.md
.changeset/thick-lizards-attack.md
libs/core/src/components/button/fab/fab.styles.ts
libs/core/src/components/content/text/text.stories.ts
libs/core/src/components/content/text/text.style.css.ts
libs/core/src/components/content/text/text.ts
libs/core/src/components/datepicker/datepicker.styles.ts
libs/core/src/components/dropdown/dropdown.styles.ts
libs/core/src/components/layout/card/card.stories.ts
libs/core/src/components/layout/card/card.style.css.ts
libs/core/src/components/theme/theme.stories.ts
libs/core/src/storybook-docs/style/typography.mdx
libs/core/src/tokens.style.ts
libs/tokens/src/formats.ts
libs/tokens/src/tokens/shadow/shadow.json
libs/tokens/src/tokens/typography/line-height.json
libs/tokens/src/tokens/typography/typography.json
libs/tokens/style-dictionary.config.ts

This PR updates all the typography tokens, the typography style story and all the components that have used the `gds-text` component. 
Also the typography scale is refactored and `title` sizes are removed in favor of `heading` scale to match `h1-h6` with `heading-xl` - `heading-2xs` respectively. 
Some improvements also has been done on the `gds-text` component by applying all the styling directly to the tag, better defaults and the way how the tag is created. 
This change depreciates the following typography tokens:
| Deprecated Sizes                                   |
|----------------------------------------------------|
| label-overline                                      |
| label-input-medium                                  |
| label-input-large …

Tokens: Typography 

---

.changeset/four-beds-accept.md
libs/core/src/components/menu-button/menu-button.ts

There was a request to be able to customize text-alignment of the menu button. Usually, this can be done by styling the slotted element, but in the menu button the slot itself needs some default styles which sets it to `display: inline-block`.
This PR adds a CSSPart hook for the main slot so that it can be customized.

Menu button: Expose CSSPart for main slot

---

.changeset/gentle-days-clap.md
apps/core-lib-dev/src/app/calendar.element.ts
libs/core/src/components/calendar/calendar.styles.ts
libs/core/src/components/calendar/calendar.trans.styles.scss
libs/core/src/components/calendar/functions.ts

This PR sets the minimum number of week rows to 6, even for months only spanning over 5 weeks. This prevents height in the calendar from changing while stepping through months. Solution for #1441

Fix calendar jumping when changing months 

---

.changeset/wicked-rules-camp.md
libs/core/src/storybook-docs/concepts/declarative-layout.mdx
libs/core/src/utils/decorators/style-expression-property.ts
libs/core/src/utils/helpers/style-expression-parser-tester.ts
libs/core/src/utils/helpers/style-expression-parser.test.ts
libs/core/src/utils/helpers/style-expression-parser.ts

This PR adds support for specifying pseudo selectors like `:hover`, `:focus`, etc, in Style Expression Properties.
For example: 
```html
<gds-card padding="xs; hover: xs s; >l { s m; hover: xl }"></gds-card>
```
Sub-selectors are specified by prefixing a value sequence with `xxx:`, and selector/value sequences are terminated by `;`
The sub-selector will then be appended/merged with the base selector, ie `:host(:xxx)` or `.some-sel:xxx`. The `;` is only mandatory when there are more than one sequence, meaning that this upgrade will be backwards-compatible with existing expressions.
Here is a slightly more realistic example, changing the border and padding on hover:
```html
<gds-card
radius="s"
border="4xs/l2-stroke-primary; hover: s/l2-stroke-primary"
padding="xl; hover: l" …
```

Add support for pseudo-selectors in Style Expression Properties

---

.changeset/weak-wolves-fix.md
libs/chlorophyll/scss/components/themes/_mixins.scss
libs/chlorophyll/scss/tokens/_shame.scss

Our Rspack build gave warnings that we were using deprecated features from Chlorophyll:
```bash
WARNING in ./src/components/spinner/spinner.scss (../../../node_modules/css-loader/dist/cjs.js!../../../node_modules/sass-loader/dist/cjs.js!./src/components/spinner/spinner.scss)
⚠ ModuleWarning: Deprecation Warning on line 313, column 20 of file:///<REPO>/node_modules/@sebgroup/chlorophyll/scss/tokens/_shame.scss:313:20:
│ transparentize() is deprecated. Suggestions:
│
│ color.scale($color, $alpha: -83%)
│ color.adjust($color, $alpha: -0.83)
│
│ More info: https://sass-lang.com/d/color-functions
│
│ 313 |   --border-color: #{transparentize($black, 0.83)}; // #CECECE against white
```
This should get rid of these warnings. 
I don't know how to test this, would be appreciated if you could …

chore(chlorophyll): change transparentize to color.adjust

---

libs/react/src/lib/slider/slider.mdx
libs/react/src/lib/slider/slider.stories.tsx

Slider storybook for react now shows label and sublabel, along with default value and a big number example.
Will make it easier to understand and bug test slider in react. Now is much more similar to the examples in Angular.

Better react slider examples

---

.changeset/wet-cows-begin.md
libs/core/src/components/layout/grid/grid.ts

This pull request includes changes to the `@sebgroup/green-core` package and the `GdsGrid` component to align with the CSS specification for the `gap` property. The most important changes include updating the `gap` property handling and modifying the `GdsGrid` component to switch the order of row and column values.
Modifications to `GdsGrid` component:
* [`libs/core/src/components/layout/grid/grid.ts`](diffhunk://#diff-1afc0b4bc6a6dc96b354526bfd9f753b3727e8d75ce5ddeb2b6c5d52e4918ad5L46-R47): Changed the `styleTemplate` function to switch the order of `rowGap` and `colGap` values to align with the CSS specification. (`[libs/core/src/components/layout/grid/grid.tsL46-R47](diffhunk://#diff-1afc0b4bc6a6dc96b354526bfd9f753b3727e8d75ce5ddeb2b6c5d52e4918ad5L46-R47)`)

grid gap fix

---

.changeset/pink-sloths-walk.md
libs/core/src/gds-element.ts
libs/core/src/utils/helpers/custom-element-scoping.ts

This PR refactors how the `gds-element` attribute is set on each gds element. Now it is set by the `gdsCustomElement` instead of on `connectedCallback()`. This makes it work even if the component is registered under a different element name, and also improve performance a bit since it no longer needs a lookup in the registry for each component instance.

Refactor how `gds-element` is set

---

.changeset/olive-ads-unite.md
libs/core/setup-jest.js
libs/core/src/components/segmented-control/segment/segment.style.css
libs/core/src/components/segmented-control/segment/segment.ts
libs/core/src/components/segmented-control/segmented-control.stories.ts
libs/core/src/components/segmented-control/segmented-control.style.css
libs/core/src/components/segmented-control/segmented-control.test.ts
libs/core/src/components/segmented-control/segmented-control.trans.styles.css
libs/core/src/components/segmented-control/segmented-control.ts
libs/react/.babelrc

This change refactors a large chunk of the Segmented Control implementation:
- Rewrite layout code to use `css-scroll-snap`
- Remove `seg-min-width`
- Add style expression properties to `gds-segment` for size control
Related to #1603

Refactor Segmented Control

---

.changeset/happy-ads-look.md
libs/core/src/components/dropdown/dropdown.ts

This fixes an issue where the whole page will scroll when opening the Dropdown

Dropdown scrollIntoView only after `updateComplete`

---

.changeset/calm-fireants-hear.md
libs/core/src/utils/helpers/custom-element-scoping.ts

This PR refactors the element lookup table as a global singleton rather than a module-scoped object. This should help in module federated scenarios where code has been split up into multiple dynamically loaded modules.
An added benefint is that it now becomes easier to troubleshoot scoping related issues, since you can simply inspect the singleton:

Refactor the element lookup table to a global singleton

---

.changeset/real-ways-brush.md
libs/core/src/components/badge/badge.style.ts
libs/core/src/components/content/divider/divider.style.ts
libs/core/src/components/content/text/text.style.ts
libs/core/src/components/media/img/img.style.ts
libs/core/src/components/media/video/video.style.ts
libs/core/src/components/tooltip/style/tooltip.styles.css
libs/core/src/primitives/signal/signal.style.ts

This pull request includes several changes to the styling of various components in the `libs/core/src` directory. The primary focus is on replacing the `display: contents` property with more appropriate display properties to improve layout and rendering.

Remove Display Contents

---

.changeset/fifty-terms-boil.md
.changeset/spotty-cars-exist.md
libs/react/src/lib/form/iconButton/iconButton.tsx
libs/react/src/lib/form/input/input.stories.tsx
libs/react/src/lib/formItem/formItem.tsx

This pull request includes minor updates to the `@sebgroup/green-react` library, focusing on improving the `IconButton` component and fixing an issue with the `expandableInfoButtonLabel` in the `FormItem` component.
* Refactored the `IconButton` component to use the `Button` component internally, ensuring it supports the same features as `Button`. (`libs/react/src/lib/form/iconButton/iconButton.tsx`)
* Output the `expandableInfoButtonLabel` property to the aria-label prop of the IconButton in the `FormItem` component to fix the label issue. (`libs/react/src/lib/formItem/formItem.tsx`)
* Updated the `WithExpandableInfo` story to include the `expandableInfoButtonLabel`. (`libs/react/src/lib/form/input/input.stories.tsx`)
* Added a patch changeset for fixing the `expandableInfoButtonLabel` …

Fix `expandableInfoButtonLabel`

---

.changeset/tame-gifts-approve.md
libs/angular/src/lib/accordion/accordion-list-item.component.html
libs/angular/src/lib/accordion/accordion-list-item.component.ts
libs/angular/src/lib/accordion/accordion.stories.ts
libs/angular/src/lib/accordion/documentation.mdx

The aria-level (heading level) can now be set in Angular. Same as React can.
Closes: #1171

Accordion: Can set aria-level in angular

---

.changeset/afraid-spies-happen.md
libs/react/src/lib/modal/modal.spec.tsx
libs/react/src/lib/modal/modal.stories.tsx
libs/react/src/lib/modal/modal.tsx

All modals for React can now have custom close button text for screen readers.
(Will do modal fix for Angular next)

Modal react close text fix

---

.changeset/sharp-deers-poke.md
libs/core/src/tokens.style.ts

This pull request includes changes to the `libs/core/src/tokens.style.ts` file to enhance theme support by adding styles for both light and dark themes.
Enhancements to theme support:
* [`libs/core/src/tokens.style.ts`](diffhunk://#diff-88400f14e6d2f7007fc0593775702e608d3861c5a90331645d18410fb64b8933L30-R36): Added global styles for `:root[gds-theme='light']` and `:root[gds-theme='dark']` to support light and dark themes respectively.

Enable Color Tokens on Root using `gds-theme` attribute

---

.changeset/heavy-fans-fry.md
.changeset/rare-mails-live.md
libs/react/src/lib/dropdown/dropdown.tsx
libs/react/src/lib/modal/modal.tsx

This PR makes it possible to disable bodyScrollLock in modals. This is useful particularly on iOS, where the scroll lock can prevent scroll in undesired areas.
Related: #1742

Make bodyScrollLock optional in React modal

---

.changeset/random-file-name.md
libs/tokens/src/formats.ts
libs/tokens/src/tokens/2016/colors.json
libs/tokens/style-dictionary.config.ts

In this PR:
- Add custom formatting for scss varaibles so that dark mode gets picked up correctly
- Correct color value for `dark-blue-1`

Fix 2016 scss vars

---

.changeset/fuzzy-bulldogs-dream.md
.changeset/wild-stingrays-swim.md
libs/core/src/components/theme/theme.test.ts
libs/core/src/components/theme/theme.ts
libs/core/src/storybook-docs/concepts/tokens.mdx
libs/core/src/storybook-docs/style/colors.mdx

This PR adds a Tokens section under Concepts, and also fleshes out the Colors documentation a bit more.
It also includes som fixes to GdsTheme:
- Fix a bug where light-mode variables remained when switching to dark mode
- Add the rest of the tokens. Previously `GdsTheme` only included color tokens. Check the new Tokens doc to see why this is useful.

Add concept documentation about tokens

---

.changeset/light-queens-kiss.md
libs/core/src/components/datepicker/datepicker.trans.styles.scss

Line height set to 20px for both react and angular, just like the design have it.
Fixes: #1609

Datepicker label height fix

---

libs/chlorophyll/.storybook/preview.ts
libs/chlorophyll/stories/introduction/how-to-use.mdx
libs/chlorophyll/stories/introduction/intro.mdx

This PR contains a fix to show the first story in the chlorophyll storybook instead of Accordion docs as well as some updated docs.

Fix chlorophyll storybook

---

libs/angular/src/v-angular/modal/dialog/dialog.component.html
libs/angular/src/v-angular/modal/dialog/dialog.component.scss
libs/angular/src/v-angular/modal/dialog/dialog.component.ts

Added wrapping element with class `.modal-dialog__wrapper`, in which we include the wrapper mixin.

fix: wrap dialog with wrapper element

---

.changeset/forty-starfishes-roll.md
libs/chlorophyll/scss/components/tabs-bar/_mixins.scss
libs/react/src/lib/tabs/tabs.stories.tsx

Closes: #947
Also makes the React storybook examples have spacings like the Chlorophyll have.

Not selected tabs now have same size as selected

---

libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.ts
libs/angular/src/v-angular/dropdown/dropdown.component.ts

Fixed type of input `thook` in `DropdownComponent` and `DropdownListComponent` to include `null` and `undefined`

Dropdown/DropdownList: Fixed thook type

---

libs/angular/src/v-angular/dropdown/dropdown.component.scss
libs/angular/src/v-angular/dropdown/typeahead/typeahead-input/typeahead-input.component.ts
libs/angular/src/v-angular/dropdown/typeahead/typeahead.directive.ts

- Added missing input for typeahead directive `emptyOptionLabel`.
- Update position for [hidden].
- Error converting null to object.

Typeahead: Added emptyOptionLabel Typeahead input

---

libs/chlorophyll/README.md

- Updated the `<h1>` heading in the README file:  
- **Previous:** `<h1>@sebgroup/green-core</h1>`  
- **Updated:** `<h1>@sebgroup/chlorophyll</h1>`
- Reflect the updated project name to align with the current naming convention.
- No functional impact; this change only updates the README documentation.

update README heading for chlorophyll lib

---

.changeset/pink-otters-leave.md
libs/core/src/components/text/text.ts

Instead of redefining certain props on `GdsText`, I think it makes sense to inherit all the base props from `GdsContainer` instead. Although this adds a bit more overhead to `GdsText`, it is more performant than being forced to wrap it in a container.

GdsText: Inherit from GdsContainer

---

.changeset/healthy-dragons-bathe.md
libs/tokens/src/formats.ts

Other spacing tokens are still outputted as `px`

Transform text tokens to `rem` in CSS variables

---

.changeset/five-pillows-train.md
libs/react/package.json

This update makes it possible to use `@sebgroup/green-react` with React 19 without complaints from NPM.
Note, however, that the library is still not thoroughly tested with React 19, and all our unit tests still run against React 18. So proceed with caution.

Add React 19 as peer dependency

---

.changeset/fresh-paws-hug.md
libs/chlorophyll/scss/components/form/checkbox/_mixins.scss
libs/chlorophyll/scss/components/form/radio/_mixins.scss
libs/chlorophyll/scss/tokens/_colors.scss

This PR alters the current 2016 checkbox & radio hover styles and adds our 2016 color tokens.
There's an issue on mobile where the hover styles make it look like multiple items are selected. 
We need to update Figma aswell.

Checkbox & Radio hover styles

---

.changeset/stupid-turtles-cheer.md
apps/angular-lib-dev/src/app/app.module.ts
apps/angular-lib-dev/src/app/form/form.module.ts
libs/angular/src/lib/shared/core-renderer/core-renderer.spec.ts
libs/angular/src/lib/shared/core-renderer/core-renderer.ts
libs/core/src/storybook-docs/guides/installing.mdx

This PR adds a provider for supporting animations when using `NggCoreRenderer`
Before:
```ts
@NgModule({
declarations: [AppComponent],
imports: [BrowserAnimationsModule, BrowserModule, AppRoutingModule],
providers: [{
provide: RendererFactory2,
useClass: NggCoreRendererFactory,
}],
bootstrap: [AppComponent],
})
export class AppModule {}
```
Now:
```ts
@NgModule({
declarations: [AppComponent],
imports: [BrowserAnimationsModule, BrowserModule, AppRoutingModule],
providers: [provideCoreRendererWithAnimations()],
bootstrap: [AppComponent],
})
export class AppModule {}
```
Or, if you don't need animations:
```ts
@NgModule({
declarations: [AppComponent],
imports: [BrowserModule, AppRoutingModule],
providers: [provideCoreRenderer()],
bootstrap: [AppComponent],
})
export class AppModule {}
``` …

NggCoreRenderer animations support

---

.changeset/gentle-clocks-happen.md
libs/core/src/components/datepicker/datepicker.ts
libs/core/src/components/dropdown/dropdown.ts
libs/core/src/components/popover/popover.ts

This PR changes the default behavior of popovers to shift instead of flip when there is limited space. This will cause the popover to render on top of the trigger element, but it will use space more optimally.
Here is an example of the old behavior. There is limited space below and above, the popover flips and resizes to fit above the trigger, and thus leaves very little space for the listbox:
And here is how it behaves now. Instead of flipping and resizing, the popover shifts, covering the trigger but allowing more space for the listbox, which arguably is the most important element for the user:

Popover: Change default position strategy to shift rather than flip

---

.changeset/moody-zoos-warn.md
libs/angular/src/v-angular/dropdown/dropdown.component.scss
libs/angular/src/v-angular/dropdown/dropdown.stories.ts

Fix for where the dropdown list was rendered "below" other inputs:
Added example to existing story `ComboTemplate` for testing changes.

fix: ensure dropdown-list is rendered above other inputs

---

.changeset/bright-ducks-end.md
.changeset/gentle-cheetahs-impress.md
libs/core/src/components/dropdown/dropdown.test.ts
libs/core/src/components/dropdown/dropdown.ts
libs/core/src/components/popover/popover.ts
libs/core/src/primitives/listbox/option.styles.ts
libs/core/src/primitives/listbox/option.trans.styles.scss
libs/core/src/primitives/listbox/option.ts

This PR fixes:
- Issue when som elements gets `aria-hidden` even though they are in focus
- Issue with Popover positioning obscuring the input field when using the `combobox` option.

Dropdown: Fix `aria-hidden` issues and combobox positioning

---

.changeset/rotten-numbers-vanish.md
libs/core/src/components/div/div.ts
libs/core/src/components/text/text.stories.ts
libs/core/src/components/text/text.ts

This PR adds a new property on the `gds-div` by extension making it available on the `gds-text` component. 
Also the ellipsis style it's passed now to the `[tag]` instead of the host in order to make ellipsis same font size as the content.

Text: add `overflow-wrap`

---

.changeset/dull-falcons-vanish.md
libs/core/src/primitives/field-base/field-base.component.ts
libs/core/src/primitives/field-base/field-base.styles.ts

Conditionally changing DOM structure around slots likely caused a recursion of slotchange events, which may have tripped up ZoneJs in Angular.
Changing to a conditional classname solves the issue.

Fix Textarea crash in Angular

---

.changeset/proud-planes-allow.md
libs/angular/src/v-angular/table/table.component.html
libs/angular/src/v-angular/table/table.component.scss
libs/angular/src/v-angular/table/table.mock.ts
libs/angular/src/v-angular/table/table.models.ts

At the moment, the v-angular table is not adapted for mobile layouts, but our MFEs now require it. So, I decided to update the current table component layout according to the provided sketches. Later, it might be better to have a different component, similar to an accordion or something similar, but for now, I believe these changes will be sufficient.
The idea is to switch the regular table to one with expandable functionality on mobile views. However, table data modification and table settings will be controlled from the MFE side, depending on screen size. From the library side, only the layout will be updated. If the table is already expandable, no additional logic is required.
Required functionality:  
- Dynamically hide/show labels and data
Web view (already exists):
Mobile view (now …

Updated v-angular table for mobile view

---

.changeset/brown-tools-care.md
libs/angular/src/v-angular/table/table.component.html
libs/angular/src/v-angular/table/table.component.scss

- Lighthouse was throwing accessibility warnings for the table.
- Updated the breakpoint pixel range for the mobile view according to Angular’s "@angular/cdk/layout".

MABFF-1090 Table a11y warnings

---

.changeset/silver-bugs-hide.md
libs/angular/src/lib/shared/core-control/core-checkbox.directive.ts
libs/angular/src/lib/shared/core-control/core-control.directive.ts
libs/angular/src/lib/shared/core-control/core-control.spec.ts

This PR solves an issue where console errors appeared when green-core form controls where used in Angular outside of reactive forms (i.e, without `formControlName` directive)

Update NggCoreControl directive selectors

---

.changeset/neat-bags-sort.md
libs/core/src/components/dropdown/dropdown.component.ts

Fixes issue where markup was included in the `aria-label` attribute and got read up in raw form by some screen readers.

Dropdown: Fix trigger label when custom template is used

---

.changeset/wide-planes-tap.md
libs/angular/src/v-angular/drag-drop/drag-drop.component.scss

Prevent file name of overflowing if it contains a string that can't be broken following "normal" line break rules.

Drag-drop: Prevent overflow for file name

---

.changeset/lovely-beers-care.md
libs/chlorophyll/scss/components/table/_mixins.scss

After CX designer's review, there was a request to remove the table line/border around the table header.

MABFF-1150 From design review: Remove line/border around table header

---

.changeset/fifty-candles-smoke.md
libs/core/src/components/button/button.component.ts
libs/core/src/components/datepicker/datepicker.component.ts
libs/core/src/components/filter-chips/filter-chips.component.ts
libs/core/src/components/form-summary/summary.stories.ts
libs/core/src/components/form/form-control.ts
libs/core/src/components/input/input.component.ts
libs/core/src/components/radio/radio-group/radio-group.component.ts
libs/core/src/components/select/select.component.ts
libs/core/src/components/textarea/textarea.component.ts

This PR removes the base implementation of `focus()` in `GdsFormControl`, since it otherwise blocks access to the native `focus()` method from child classes.
This prevented programmatic focus from working correctly with some components, such as Checkbox.
Each form control now needs to implement this locally if required.

Focus handling: Fix issues with programmatic focus shifting

---

.changeset/thin-walls-lie.md
libs/angular/src/v-angular/toast/toast.component.scss

CX required changes after design implementation review [PGP-51554](https://jira-general.sebank.se/browse/PGP-51554)
Before:
After this PR changes:

Toast: Full width on mobile

---

.changeset/large-mice-travel.md
libs/angular/src/v-angular/i18n/i18n.json
libs/angular/src/v-angular/modal/dialog/dialog.component.html
libs/angular/src/v-angular/modal/dialog/dialog.component.scss
libs/angular/src/v-angular/modal/dialog/dialog.component.ts
libs/angular/src/v-angular/modal/dialog/dialog.stories.ts
libs/angular/src/v-angular/modal/fold-out/fold-out.component.html
libs/angular/src/v-angular/modal/fold-out/fold-out.component.scss
libs/angular/src/v-angular/modal/fold-out/fold-out.component.ts
libs/angular/src/v-angular/modal/fold-out/fold-out.stories.ts
libs/angular/src/v-angular/modal/modal.types.ts

- Added `listWidth` property to `fold-out` component. This is mainly to be able to accommodate if the list is wider than the actual component, resulting in unwanted line breaks.
- Options `fit-content`, `max-content`, `min-content`, `auto` for flexibility
- Defaults to `fit-content`, which is how it was previously
`<nggv-fold-out style="width: 30px;">` **width: fit-content**
`<nggv-fold-out style="width: 30px;" listWidth="max-content">` **width: max-content**
---
- Added new submit button `danger` to `dialog` component. Has priority 2 of 4 (less than "regular" submit, more than "alternatives")
- Changed name of old class of `danger` to `danger-confirm`, to be able to give class name `danger` to new button
**Old**
**New**

listWidth property to fold out component - danger button to dialog component

---

.changeset/big-coats-fry.md
libs/tokens/src/templates/jvm/enum-class.template.js

Fix a typo in the template where a ")" was used instead of a "}"

Fix JVM tokens format

---

.changeset/large-llamas-impress.md
libs/chlorophyll/scss/components/alert-ribbon/_mixins.scss
libs/chlorophyll/scss/components/pagination/_mixins.scss

Was black color on black background for the selected tab in pagination.
Bug reported in GDS->General.
Color base-000 is not used and becomes black.
Edit: Same error in Alert success. Should be white text on green, not black text on green. Checked the old design.

Pagination+Alert: Color fix

---

.changeset/long-frogs-cry.md
.storybook/preview.scss
libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.html
libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.scss
libs/angular/src/v-angular/dropdown/dropdown-list/dropdown-list.component.ts
libs/angular/src/v-angular/dropdown/dropdown.component.html
libs/angular/src/v-angular/dropdown/dropdown.component.ts
libs/angular/src/v-angular/dropdown/dropdown.stories.ts

In consumer project green-core is not updated to the newest version (V2).
Also, in the consumer project there is an additional styling for the dropdowns applied, so this change with portal breaks styling in the consumer project and to fix, it will require time.
To handle green migration to v2 correctly, this change will be reverted for now.

Revert "V-Angular Dropdown: move dropdown list to CDK portal (#2411)"

---

.changeset/four-guests-roll.md
libs/core/src/components/checkbox/checkbox.component.ts

This PR fixes an intermittent tree-shaking issue that pos up in Angular from time to time. Seems to happen only when certain combinations of components are imported.
This change fixed the issue in my local test project with Angular 20.

Checkbox: Fix tree-shaking issue

---

.changeset/many-dragons-return.md
libs/core/src/components/filter-chips/filter-chips.component.ts

This PR fixes an issue where the inital `value` didn't reflect correctly in the rendered state of the component, in particular when using with Angular.

Filter chips: Fix initial state issue
